### ISSUE TITLE
Creating a cluster with an invalid volume type proceeds to create the CloudFormation stack

### ISSUE THREAD

**Issue by cPu1** [weaveworks/eksctl#1046]
**What happened?**
`eksctl create cluster --node-volume-type=non-existing-volume-type` attempted to create a CloudFormation stack with that volume type instead of validating it and returning an error before attempting to create any resources. The stack creation eventually failed because that volume type is invalid.

**What you expected to happen?**
`eksctl create cluster` should validate the volume type against a list of supported volumes and fail fast before attempting any resource creation.

**How to reproduce it?**
```shell
eksctl create cluster --node-volume-type=non-existing-volume-type
```

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.2.0"}
$ kubectl version
Not applicable
```
This issue exists in  prior versions of eksctl also.

**Logs**
```
$ eksctl create cluster --node-volume-type=non-existing-volume-type
...
[✖]  AWS::AutoScaling::AutoScalingGroup/NodeGroup: CREATE_FAILED – "You must use a valid fully-formed launch template. Unsupported volume type 'non-existing-volume-type' for volume creation. (Service: AmazonAutoScaling; Status Code: 400; Error Code: ValidationError; Request ID: <>)"
...
```

**Comment by errordeveloper** [comment]
To me this kind of falls under #488. Same happens if you try `--node-type=m99.xsweet`, maybe we should open another issue for that or generalise this one. I am not sure if solving volume type validation is useful on it's own, we should probably be looking at instance types also. However, I've not seen any user complaints about this.

Unlike instance types, there are only a few volume types and new ones don't get added as often, so we can write simple validation logic and just produce an error. While with instance types we might want to use a regex, and perhaps only produce an informative warning, as user may know what they are doing. Or we may wish to consider adding a flag to bypass validation.

**Comment by cPu1** [comment]
Agree with your points. Fixing this would require much less code once we have #488 in place. This along with instance type validation and other similar forms of validation can all go in the same issue.
