### ISSUE TITLE
Add experimental environment variable

### ISSUE THREAD

**Issue by gemagomez** [weaveworks/eksctl#1055]
Add support for experimental features by using an environment variable. 

A suggestion for the name is `EKSCTL_EXPERIMENTAL`. This will be a boolean with value `True` if experimental is enabled. 

#### After the conversation we settled on
 `EKSCTL_EXPERIMENTAL=true`

### Checklist
- [ ] Code compiles correctly (i.e `make build`)
- [ ] Added tests that cover your change (if possible)
- [ ] All unit tests passing (i.e. `make test`)
- [ ] Added/modified documentation as required (such as the `README.md`, and `examples` directory)
- [ ] Test case added to ensure the flag works. I.e. add a test feature eksctl test meant to remain experimental and make sure via test case that when it is invoked with EKSCTL_EXPERIMENTAL enabled it is reachable, and it is not reachable if the variable is not there.

**Comment by errordeveloper** [comment]
I think this is a nice model, Docker CLI used [this approach](https://docs.docker.com/engine/reference/commandline/cli/#environment-variables).

More specifically, `True` is rather Pythonic. I think `EKSCTL_EXPERIMENTAL=enabled` reads nicely, I'd vote for that, it's also what Docker CLI uses.

**Comment by gemagomez** [comment]
`EKSCTL_EXPERIMENTAL=enabled` it is then, thank you!

**Comment by rndstr** [comment]
to avoid confusion we could support all three options:

- `enabled`
- `true`
- `1`

but only use `enabled` in documentation

**Comment by whereisaaron** [comment]
Hey, this is not JavaScript, let's not try to invent too many truthy/falsey values 😄 

@errordeveloper does this read as well?
```
EKSCTL_EXPERIMENTAL_ENABLED=true
```

I'd advocate for consistency; pick an approach and use it consistently throughout `eksctl`. Since `eksctl` aims to be primary based around a YAML config file, could we be consistent with that?

YAML 1.2 [uses only uses true/false](https://yaml.org/spec/1.2/spec.html#id2803629), which matches JSON, and was to fix the mistakes of YAML 1.1/1.0 where life was complicated because [all these values](https://yaml.org/refcard.html) [were possible](https://yaml.org/type/bool.html):
```
{ Y, true, Yes, ON  }    : Boolean true
{ n, FALSE, No, off }    : Boolean false
```

I think adding e.g. enabled/disabled, 1/0, yes/no, y/n, etc. only seeds user confusion. And documenting only some values but supporting other undocumented values doesn't seem helpful to avoid confusion either.

"So... I see these truthy values here for `EKSCTL_EXPERIMENTAL`, I guess I can use them for other settings too?"
```
NodeGroupIAMAddonPolicies:
  properties:
    albIngress: true
    appMesh: enabled
    autoScaler: 1
    certManager: 0
    cloudWatch: maybe
    ebs: affirmative
    efs: 2
    externalDNS: activated
    imageBuilder: engage!
```
🤣🤣🤣 (because four would be too many)

**Comment by errordeveloper** [comment]
That is a very good idea, Aaron! Thank you for the input :)

**Comment by toothbrush** [comment]
I'm glad to see this coming along, especially since i'm clamouring for #1039 😃. Thanks all! 🎉 

I don't feel very strongly either way, but how would we feel about having a way to configure experimental on/off in a config file, too?  I ask because i've scripted our EKS deployment with `eksctl` and while it's completely possible to add environment variables to that, i find (personal taste) that having this sort of setting as a command-line flag or rc value looks nicer in e.g. deploy scripts.  Or even inside the values file we currently pass to `eksctl -f <file>` — although i agree that it's not really a per-cluster concern, so that's probably not super appropriate.  Just brainstorming.

**Comment by errordeveloper** [comment]
> although i agree that it's not really a per-cluster concern, so that's probably not super appropriate

Yes, and more generally it's about more general behaviour. Additionally, in different versions of `eksctl` there will be different experimental features that evolve in their own ways, so having an option in a config file wouldn't serve that same thing will happen. Experimental features mean to evolve quickly and it's hard to say whether a dedicated config file will be needed or not.
