### ISSUE TITLE
Private Subnets for Worker Nodes

### ISSUE THREAD

**Issue by mwelch-ptc** [weaveworks/eksctl#120]
Feature Suggestion: eksctl should favor, or at least offer the option of, creating a VPC for the EKS cluster with private subnets for worker nodes. 

I was surprised to find that the nodes created via eksctl all had internet facing IP addresses assigned to them. Perhaps there is a technical reason for this of which I am unaware, however the EKS documentation seems to encourage the use of a private subnet for worker nodes as seen here: https://docs.aws.amazon.com/eks/latest/userguide/create-public-private-vpc.html

**Comment by shatil** [comment]
Great project! I'd love to pitch in since I'd like to test this out for our company. The private subnets are a must for me, too.

In trying to understand how this works, I see that `cfn.go` references `amazonEksVpcSampleYamlBytes`, which sources the sample YAML from `assets/1.10.3/2018-07-18/amazon-eks-vpc-sample.yaml`.

I imagine it was expedient to hardcode a sample three-AZ template to get going, and in #127, it looks like you're exploring goformation, and it seems prudent to wait on that, rather than modifying that giant subnets YAML by hand to add `n` public subnets, NAT gateways sitting on public subnets, and a route table point `0.0.0.0/0` on the private subnets to the NAT gateway those together.

**Comment by errordeveloper** [comment]
@shatil I've missed you comment, if you are still interested to contribute, perhaps you could help by testing/reviewing #287? I'm hoping to get this into the next release.
