### ISSUE TITLE
Revisit gitops `--git-private-ssh-key-path` argument

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/eksctl#1211]
`--git-private-ssh-key-path` is used by `eksctl install flux` to clone the repository where to put the flux manifests.

However, it's only use seems to be in tests. Additionally, that ssh key is not propagated to Flux during installation (so that Flux can use it to read from the repository).

I think we should either remove the flag or propagate the ssh key for Flux to use during execution.

**Comment by 2opremio** [comment]
Related https://github.com/weaveworks/eksctl/issues/1180

**Comment by 2opremio** [comment]
Also, note that `ssh -i` doesn't exclusively use that the provided key to connect. If you have `IdentityFile` entries in your config file it will use those too and try them first. 

In GitHub, since the keys are used for authentication, this will result in the `Indentity` config file entries being prioritized and can result in authentication problems.

**Comment by errordeveloper** [comment]
To me this reads a it should be part of #1213, which addresses broader concerns. Do you agree?

**Comment by 2opremio** [comment]
Yes, probably, I don't think it's a feature.

**Comment by 2opremio** [comment]
Related #1213

**Comment by willemveerman** [comment]
Rather than having flux authenticate with an SSH key, I think it would be better to use an access token.

In BitBucket terminology these are called 'app passwords'

I think this would be better because, in the first instance, a token is the authentication mechanism designed for applications - SSH keys are intended for users and flux is not a user per se.

Each access token can be configured to have a specific set of permissions.

Furthermore, the token itself is a short string, so it is easier to deal with than an SSH key, which must be properly formatted in order to work correctly. For example, when one stores SSH keys in AWS Parameter Store secrets, it is difficult to get the key into a variable in the correct format; often one has to write the key to a file first and then read the file, which is less secure. With an access token, you can store the value in parameter store and then easily pass it to the `kubectl create secret` command.

Here's some example code from one of our pipelines:

```
        bitbucket_flux_app_password = os.environ["BITBUCKET_FLUX_APP_PASSWORD"]

        self.run_cmd("kubectl create secret generic "
                     "flux-git-auth -n flux "
                     "--from-literal=GIT_AUTHUSER=platform-engineering "
                     f"--from-literal=GIT_AUTHKEY={bitbucket_flux_app_password}")

        self.run_cmd("helm repo add fluxcd https://charts.fluxcd.io")

        self.run_cmd(f"helm upgrade -i flux fluxcd/flux "
                     "--set git.url=https://$(GIT_AUTHUSER):$(GIT_AUTHKEY)@bitbucket.org/org/repo.git "
                     "--set env.secretName=flux-git-auth "
                     "--set git.user=flux "
                     "--set git.email=user@domain.com "
                     "--set git.pollInterval=45s "
                     f"--set git.path=environments/{env} "
                     "-n flux")
```

**Comment by michaelbeaumont** [comment]
@martina-if can we get rid of this flag?

**Comment by martina-if** [comment]
I think this could still be useful for when the git provider is not github.

**Comment by Callisto13** [comment]
Closing due to https://github.com/weaveworks/eksctl/issues/2963
