### ISSUE TITLE
`gitops apply` git urls should be ssh

### ISSUE THREAD

**Issue by gemagomez** [weaveworks/eksctl#1212]
**What happened?**

Tried to run `gitops apply` with http urls as parameters and it fails. 

**What you expected to happen?**

`eksctl` should enforce the right format of the git parameters and return a meaningful error if the format is not met.

**How to reproduce it?**

Run `eksctl gitops apply` with git urls in http format, rather than ssh format.

**Comment by errordeveloper** [comment]
Generally speaking, I think any valid git URL should work. However, I am aware that due to a number of reasons we've been forcing Flux user to requite SSH URLs.

**Comment by errordeveloper** [comment]
So are we saying that we will have to allow only SSH URLs for now? There is a number of implications as in some organisations use of SSH ports is not permitted.

**Comment by errordeveloper** [comment]
@gemagomez do you have more context of what exactly didn't work? Just to be clear...

**Comment by 2opremio** [comment]
This applies to `install flux` as well

**Comment by cPu1** [comment]
`eksctl gitops apply` delegates to the git CLI for cloning the repo, which does support HTTPS URLs by prompting you to enter your credentials. If you have 2FA on GitHub enabled (we all do since joining the weaveworks org requires having it enabled), your regular credentials won't work and you'd need to create a [personal access token](https://github.com/settings/tokens) and use it as your username (leaving the password blank).

Alternatively, you could add this directive to your gitconfig to rewrite HTTPS URLs to SSH:
```
url "git@github.com:"]
        insteadOf = https://github.com/
```

**Comment by cPu1** [comment]
The UX for using HTTPS URLs in `eksctl gitops apply` though is cumbersome as you'd be prompted for credentials for every remote git operation (clone, push etc)

I tried `eksctl gitops apply` with an HTTPS URL and it successfully ran to completion.

**Comment by 2opremio** [comment]
> I tried `eksctl gitops apply` with an HTTPS URL and it successfully ran to completion.

Yeah, but Flux won't work because the credentials are not currently propagated to it.

It is theoretically possible to make everything work with `https` URLS but, as I mentioned privately, right now:

1. I private https repos, Git will ask you for credentials to push to the repo, which will cause the operation to time out.
2. The http credentials won't be passed to Flux and it won’t work at all if the repo is private. Autoupdates definitely won't work even if the repo is public and I am not sure if it will be able to run at all. I will work with a public repo _if_ Flux is run in readonly mode (which still don't currently have support for).

(1) Is easily fixable by not enforcing a timeout. As @rade pointed out privately, this is also needed in situations in which ssh is used but manual intervention is required (password-based authentication, passkey protected private key not added to `ssh-add` etc ...)

(2) Is not that easy:
a. We could add UX support for http credentials but this will likely overcomplicate the UX
b. We could support http for public repos, when Flux is in readonly mode (figuring out whether the repo is public may be tricky though).
c. We could transform http URLs into ssh URLs (which seems a terrible approach).
d. We could enforce an ssh URL for now

**Comment by 2opremio** [comment]
I would propose getting rid of the timeouts (this probably requires dealing with https://github.com/weaveworks/eksctl/issues/1222)  and going for (d)

**Comment by errordeveloper** [comment]
As far as I am concerned, we just need to acknowledge our informed decision, which maybe only an interim one. At this stage we should make very simple choices.

Given HTTPS URL, we either:
- produce an error and exit
- produce a warning but let use proceed if they know what they are doing, e.g. the repo is public or URL has username and password (and they are happy with it that way)

> I will work with a public repo if Flux is run in readonly mode (which still don't currently have UX support for).

I've had it working with read-only access to repos multiple times, as long as you don't care about image update functionality. There is also tracking tag, but I believe that's also not crucial to basic functionality.

**Comment by cPu1** [comment]
>Yeah, but I don't think Flux won't work because https credentials are not currently propagated to it.

I was referring to this issue:
>Tried to run gitops apply with http urls as parameters and it fails.

The command itself doesn't fail but in order for Flux to sync the quick-start manifests, Flux would have to be reconfigured.

**Comment by 2opremio** [comment]
> * produce an error and exit

That's what I meant by (d)

**Comment by marccarre** [comment]
Does anyone have a concrete example of `eksctl` failing with SSH on (1) from https://github.com/weaveworks/eksctl/issues/1212#issuecomment-526163555?

**Comment by 2opremio** [comment]
Here it goes:

```
manzanon:~ fons$ ssh-keygen
Generating public/private rsa key pair.
Enter file in which to save the key (/Users/fons/.ssh/id_rsa): 
Enter passphrase (empty for no passphrase): 
Enter same passphrase again: 
Your identification has been saved in /Users/fons/.ssh/id_rsa.
Your public key has been saved in /Users/fons/.ssh/id_rsa.pub.
The key fingerprint is:
SHA256:LAQbzpCdLcPNmC0EqD18xS+sQcjt0ifa+KDduQXR/BA fons@manzanon.local
The key's randomart image is:
+---[RSA 2048]----+
| ooO+XE          |
|. ++%*B.         |
|.o +=*=.         |
|. = *o++.        |
|   B.=..S        |
|  + o. .         |
| o + ..          |
|. . +.           |
|    ..           |
+----[SHA256]-----+
manzanon:~ fons$ # Add .ssh/id_rsa.pub to github
manzanon:~ fons$ EKSCTL_EXPERIMENTAL=true eksctl gitops apply --cluster fons-cluster-1 --region eu-north-1 --quickstart-profile app-dev --git-url git@github.com:2opremio/my-gitops-repo.git  --git-email fons+flux@weave.works
[ℹ]  Generating public key infrastructure for the Helm Operator and Tiller
[ℹ]    this may take up to a minute, please be patient
[!]  Public key infrastructure files were written into directory "/var/folders/zt/sh1tk7ts24sc6dybr5z9qtfh0000gn/T/eksctl-helm-pki816249845"
[!]  please move the files into a safe place or delete them
[ℹ]  Generating manifests
[ℹ]  Cloning git@github.com:2opremio/my-gitops-repo.git
Cloning into '/var/folders/zt/sh1tk7ts24sc6dybr5z9qtfh0000gn/T/eksctl-install-flux-clone-001737424'...
Enter passphrase for key '/Users/fons/.ssh/id_rsa': [✖]  cannot clone repository git@github.com:2opremio/my-gitops-repo.git: signal: killed

git@github.com: Permission denied (publickey).
```

You need to wait a fair amount of time for the git timeout to be triggered.

If you have a password protected key (which I hope you have :) ) there is no need to generate a new one.
