### ISSUE TITLE
use eksctl shared w/ a colleague

### ISSUE THREAD

**Issue by patrick-hermann-sva** [weaveworks/eksctl#1216]
a colleague and I are admins in the same aws account. If he is creating a cluster with eksctl, he can see information about it with **eksctl get cluster** and work with it... What we like to know is, is it possible to sync that cluster state over accounts that I can see/interact with 'his' clusters too?

**Comment by cPu1** [comment]
`eksctl get cluster` makes a call to the `ListClusters` AWS API, so you should be able to use that command since you're an admin. To interact with the Kubernetes cluster itself and access API server resources, you need to add the API endpoint and certificate authority data to your kubeconfig file. You can do so by issuing:
```shell
aws eks update-kubeconfig --name <cluster>
```

Additionally, the AWS user that created the cluster must add your role ARN to the `aws-auth` ConfigMap:

```shell
aws eks iamidentitymapping <args>
```

**Comment by patrick-hermann-sva** [comment]
thank you @cPu1 ! I forgot to specify a default region in aws configure... now eksctl get cluster is working fine :-)
