### ISSUE TITLE
usage of EKS Service IAM Role

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#122]
From reading [the docs](https://docs.aws.amazon.com/eks/latest/userguide/service_IAM_role.html), it appears that one doesn't have to create a unique role for each cluster.

So it would seem plausible that we can create the role only once per account, however that would require us to check whether the role is valid every time, which can be unreliable and could complicate the basic user experience even further (and is subject to ownership concerns, see also #107).

It is understood that in some scenarios user may not have the right level of access to create roles, and they would have a shared role that someone else would create for them.

Here is what we should do to help both use-cases:

1. keep current experience as is, but roll service role into the same CloudFormation stack as the cluster itself (see also #76).
2. add `eksctl utils (create|delete) shared-iam-role` that one can run once as utility (arguably this may live under `eksctl utils`)
3. add `eskctl create cluster --shared-iam-role` flag that allows passing existing role ARN which can be ours or custom (we won't manage it, but might validate against a template)

**Comment by nckturner** [comment]
It is correct that only one role needs to be created per account, but I agree it makes sense to support both use cases.  In order to fully support the use case of a user who does not have privileges to create roles, should we allow the node group instance role/instance profile to be similarly specified in a parameter and generated?  (Or, even allow nodes to be created in a separate command from the cluster, but that probably belongs in a different feature request.)

**Comment by errordeveloper** [comment]
Good point on node IAM resources. It would make sense to leave those until
we have separate node group management commands (which we will soonner or
later), or we could provide all-in-one shared IAM setup utility. All of
this should become easier after CloudFormation changes, as we will be able
to slice and dice stacks as we will.

**Comment by errordeveloper** [comment]
We can begin this by adding a field in `ClusterConfig`, so that this can be set via config file.
