### ISSUE TITLE
where does eksctl put tiller certs

### ISSUE THREAD

**Issue by derrickburns** [weaveworks/eksctl#1322]
When using the experimental `install flux` commands, I wonder where eksctl puts the generated tls certificates so that my local `helm` client to communicate with `tiller`?

**Comment by 2opremio** [comment]
The logs include the directory where the certificates are written.

For security reasons, instead of reusing the flux client certificate, I would recommend generating a new one for invoking helm. The directory contains the ca certificate and its private key, which should be enough for generating another certificate.

**Comment by 2opremio** [comment]
To generate the certificate, follow the same steps indicated in the [Helm Operator documentation](https://docs.fluxcd.io/projects/helm-operator/en/latest/tutorials/get-started.html#install-helm-tiller), but without generating a new CA certificate, that is:

```
export TILLER_HOSTNAME=tiller-deploy.flux
export USER_NAME=helm-client
echo '{"signing":{"default":{"expiry":"43800h","usages":["signing","key encipherment","server auth","client auth"]}}}' > ca-config.json
echo '{"CN":"'$USER_NAME'","hosts":[""],"key":{"algo":"rsa","size":4096}}' | cfssl gencert \
  -config=ca-config.json -ca=ca.pem -ca-key=ca-key.pem \
  -hostname="$TILLER_HOSTNAME" - | cfssljson -bare $USER_NAME
```

Where `ca.pem` and `ca-key.pem` are the ones generated by the `eksctl install flux` or `eksctl gitops apply` commands

**Comment by derrickburns** [comment]
I see `/etc/fluxd/helm-ca/ca.crt`.  How does this relate to `ca.pem` and `ca-key.pem`?

**Comment by 2opremio** [comment]
`ca.crt` is the same as `ca.pem`, flux simply expects it as `ca.crt` in the path you printed.

(I am afk and using my memory, so maybe the file we generate is actually called `ca.crt` but it shouldn't matter)

`ca-key.pem` is not used at runtime, only used by `eksctl install flux` and `eksctl gitops apply`. So, unless you saved it (as the logs suggest) you won't be able to generate a new certificate.

**Comment by 2opremio** [comment]
In other words, use the files generated when invoking `eksctl` and not the onespunted by the flux operator (as your path suggests).

**Comment by derrickburns** [comment]
I am trying to automate this.  It seems that is made difficult by the fact that the I have to parse the output of eksctl to get the directory ....  It would be nice if eksctl created the local cert and placed it in HELM_HOME.

**Comment by 2opremio** [comment]
Uhm, I am not sure we should do exactly that, since keeping the private key around may not be the best idea in terms of security. But, we could try to make it easy to automate what you need (or even directly generate another certificate for invoking helm directly)

Regardless, please create a separate issue for this. In the meantime, passing the output of the command should do until we have aore robust solution.

**Comment by derrickburns** [comment]
Thanks!
