### ISSUE TITLE
Eliminate dependence on ~/.ssh/id_rsa

### ISSUE THREAD

**Issue by derrickburns** [weaveworks/eksctl#1430]
It appears that the eksctl installer for `flux` requires access to `~/.ssh/id_rsa`.  This is undesirable.  Instead, it is preferable to allow use of a running `ssh-agent`.

**Comment by errordeveloper** [comment]
Hi @derrickburns, thanks for reporting this. Could you please elaborate a little more on what exactly makes current implementation problematic and more details on how would you like to see it working instead? Is this about having to enter the password or are you using agent forwarding?

**Comment by derrickburns** [comment]
Sure.

I tried to use eksctl in a Docker container that does not have ~/.ssh/id_rsa mounted into the container.  Instead, the container has a volume mounted that with access to ssh-agent that is running in another container. That setup works very well for other processes that are reliant on ssh. However, when I run eksctl to set up flux, it fails because it cannot access ~/.ssh/id_rsa when cloning flux.

Derrick Burns

**Comment by ecliptik** [comment]
I just ran into this too when going through the steps in the handson workshop (https://eks.handson.flagger.dev/profile/#create-a-github-repository).

I don't have a `~/.ssh/id_rsa` since my ssh keys are stored on a yubikey using the gpg-agent and are pulled from it whenever I use ssh (see https://developers.yubico.com/PGP/SSH_authentication/).

Error I'm getting  when running the **Create a GitHub repository** step is, 

```
[ℹ]  Cloning git@github.com:ecliptik/appmesh-dev
Cloning into '/var/folders/rr/92ps4p950cs_t07wqwdhvhxh0000gn/T/eksctl-install-flux-clone-526204455'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
[ℹ]  
[✖]  cannot clone repository git@github.com:ecliptik/appmesh-dev: exit status 128
```

**Comment by martina-if** [comment]
Support for using the ssh-agent was added by https://github.com/weaveworks/eksctl/pull/2083
