### ISSUE TITLE
Automate mention of external contributors during releases

### ISSUE THREAD

**Issue by martina-if** [weaveworks/eksctl#1451]
Use some tool to automate the list of the contributors that helped since the last release.

It involves at least:

  - [ ] add the chosen tool to the docker image that runs circleci and test it. This is installed with `pip install`
  - [ ] use it from the [do-release.sh](https://github.com/weaveworks/eksctl/blob/master/do-release.sh)

**Comment by mirogta** [comment]
This seems such a nice feature - would it make sense to extend goreleaser with this feature, to provide list of contributors since the last release?

No new tools would be necessary, because goreleaser is already used for eksctl anyway and everyone using goreleaser would benefit from it.

Because `eksctl` is using custom release notes via `--release-notes` I can imagine that goreleaser could then have a flag to add the list of contributorseither to the release notes generated by goreleaser or to the end of custom release notes.

**Comment by martina-if** [comment]
Thanks @mirogta ! that's a good idea!

**Comment by martina-if** [comment]
fixed via https://github.com/weaveworks/eksctl/pull/1799
