### ISSUE TITLE
Document all clusterconfig options

### ISSUE THREAD

**Issue by rndstr** [weaveworks/eksctl#1472]
**Why do you want this feature?**
I want a detailed starting point of configuration options I have. Coming across a clusterconfig with options I don't understand, I would like to look them up.

**What feature/behavior/change do you want?**
Have a section on eksctl.io to describe each clusterconfig option. Maybe we can automate this through the help of the existing [schema](https://eksctl.io/usage/schema/)

**Comment by kalbir** [comment]
So we are going to look at this in some more detail. I think we want to:

- provide documentation for the schema that outlines what the schema item is for
- provide documentation for the schema that explains what the permitted values are and how they should be specified
- automatically generate this documentation so that it can be updated as part of every relevant code change
- present the documentation in a clear way to the user, as part of the docs
- (maybe) show the mapping between CLI commands and config schema keys

Some examples that might be useful:
- [skaffold](https://skaffold.dev/docs/references/yaml/)
- [generated Kubernetes API docs](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/)

**Comment by kalbir** [comment]
Created https://github.com/weaveworks/eksctl/issues/2166 to get started on this.

**Comment by michaelbeaumont** [comment]
Using this issue to track actually adding the information and documentation for each field.

**Comment by michaelbeaumont** [comment]
Closing in favor of https://github.com/weaveworks/eksctl/issues/2340
