### ISSUE TITLE
cluster autoscaler is missing autoscaling:DescribeTags permissions

### ISSUE THREAD

**Issue by yahavb** [weaveworks/eksctl#1523]
**What happened?**
A description of actual behavior (with error messages).

**What you expected to happen?**
nodegroups roles created by eksctl are missing `autoscaling:DescribeTags` permissions causing cluster-autoscaler to fail 

**How to reproduce it?**
Deploy eksctl and enable gitops profile. cluster_autoscaler pod will be in crash loop. 

**Anything else we need to know?**
Adding `autoscaling:DescribeTags` to the node group role fixed the issue

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.8.0"}
$ kubectl version
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.11-eks-5876d6", GitCommit:"5876d6b7429820450950ade17fe7b4bf5ccada7f", GitTreeState:"clean", BuildDate:"2019-09-24T20:54:25Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}

**Logs**
Include the output of the command line when running eksctl. If possible, eksctl should be run with debug logs. For example:
`eksctl get clusters -v 4`
```
eksctl get clusters -v 4
2019-11-03T09:38:35-08:00 [▶]  role ARN for the current session is "arn:aws:iam::account:user/admin"
NAME		REGION
name	us-west-2```

**Comment by whereisaaron** [comment]
Hi @yahavb, did you also create the cluster with `eksctl` 0.8.0? Version 0.8.0 does include `autoscaling:DescribeTags` but I know it was missing a few versions earlier (because it is a new requirement for newer versions of the `cluster-autoscaler`).

https://github.com/weaveworks/eksctl/blob/0.8.0/pkg/cfn/builder/iam.go#L178-L190
```
	if api.IsEnabled(n.spec.IAM.WithAddonPolicies.AutoScaler) {
		n.rs.attachAllowPolicy("PolicyAutoScaling", refIR, "*",
			[]string{
				"autoscaling:DescribeAutoScalingGroups",
				"autoscaling:DescribeAutoScalingInstances",
				"autoscaling:DescribeLaunchConfigurations",
				"autoscaling:DescribeTags",
				"autoscaling:SetDesiredCapacity",
				"autoscaling:TerminateInstanceInAutoScalingGroup",
				"ec2:DescribeLaunchTemplateVersions",
			},
		)
	}
```

There is also an example available if you was to use new IAM Service Accounts AWS have introduced, which allows granting to roles directly to Pods, by projecting IAM Roles to Kubernetes Service Accounts, instead of using instance role and `kube2iam`/`kiam`.

https://github.com/weaveworks/eksctl/blob/master/examples/13-iamserviceaccounts.yaml
https://eksctl.io/usage/iamserviceaccounts/

**Comment by yahavb** [comment]
strange, I do use version 0.8.0. But I did upgrade the eksctl to 0.8.0 after I deployed the cluster and before I enabled the gitops profile. 
If this was already addressed we can close the issue. 
Thanks for the pod-based role reference!
