### ISSUE TITLE
eksctl enable profile should check for Flux's existence

### ISSUE THREAD

**Issue by marccarre** [weaveworks/eksctl#1534]
**Why do you want this feature?**

From #1509 onwards, `enable repo` installs Flux, and `enable profile` installs the components from the specified quickstart profile. However, should an user only run `enable profile`, nothing would get deployed.

**What feature/behavior/change do you want?**

1. Check for Flux's existence in:
    1. the Kubernetes cluster?
    2. the Git repository?
2. Either:
    1. error out mentioning that `enable repo` should be run first?
    2. print a warning mentioning that Flux couldn't be detected, and suggest that the user _may_ want to run the `enable repo` command first?
    3. install Flux directly?

**Comment by martina-if** [comment]
Is there a usecase where a user would want to prepare a repo first, and then add flux? Because in that case it would be ok to not error. 

To me, it makes sense that `enable profile` doesn't know anything about flux and just limits its responsibility to taking manifest templates from one repo and place them in another repo. It doesn't touch the cluster at all to do that. This also makes it possible to move this functionality somewhere else if we want to in the future.

**Comment by Callisto13** [comment]
I agree with martina's point, but also see the value in letting users know what it will take to have that repo "work" in their cluster.

Point 2.ii seems to be the right move.
> print a warning mentioning that Flux couldn't be detected, and suggest that the user may want to run the enable repo command first?

We should let the `enable profile` command succeed and print a clear warning about `enable repo`

**Comment by Himangini** [comment]
https://github.com/weaveworks/eksctl/issues/2963 This command is deprecated.
