### ISSUE TITLE
I use eksctl official image

### ISSUE THREAD

**Issue by cw-sakamoto** [weaveworks/eksctl#1536]
I'd like to use `eksctl` official image latest(0.8.0), [this repository](https://hub.docker.com/r/weaveworks/eksctl/tags) is collect?

If so, why is it stopped at 0.6.0?

**Comment by rodrigc** [comment]
@cw-sakamoto version 0.8.0 is here: https://github.com/weaveworks/eksctl/releases

**Comment by cw-sakamoto** [comment]
@rodrigc Thanks for your comment!
If I don't get it wrong, I think only the binaries are on the releases page, but is there a docker image...?

**Comment by marccarre** [comment]
@cw-sakamoto, @rodrigc, there unfortunately isn't any up-to-date _official_ image available at the moment. We'd like to add this to our release process but haven't taken the time to do so just yet. See also #1062, PRs or any kind of contribution always welcome, though! 😉 

And yes @cw-sakamoto, the official repository for `eksctl` Docker images is: https://hub.docker.com/r/weaveworks/eksctl/tags

For your information, @abdennour seems to have kindly created a Docker image for `0.9.0`, which we released yesterday. (Thank you @abdennour! ✨) More details are available here: https://github.com/weaveworks/eksctl/issues/1542#issuecomment-552663353.
However, as we haven't looked into this (yet), we cannot guarantee anything about it, and cannot officially endorse it, so please run it at your own risks 🙂

**Comment by abdennour** [comment]
Thank you @marccarre ! 
Images are created automatically 🎊by just modifying this [.env](https://github.com/abdennour/dockerfiles/blob/master/.env) file in [abdennour/dockerfiles](https://github.com/abdennour/dockerfiles) repo, thanks to the CI/CD of [Dockerhub](https://hub.docker.com/r/abdennour/eksctl). 

That's why, the available versions is not only the latest (`0.9.0`), but also : 
- abdennour/eksctl:0.9.0-aws-1.16.279
- abdennour/eksctl:0.8.0-aws-1.16.278
- abdennour/eksctl:0.7.0-aws-1.16.268
- abdennour/eksctl:0.7.0-aws-1.16.263
- abdennour/eksctl:0.6.0-aws-1.16.263
- dabdennour/eksctl:0.6.0-aws-1.16.246

More versions will come here: https://hub.docker.com/r/abdennour/eksctl/tags

@cw-sakamoto  

@cw-sakamoto  For now, all versions are up-to-date. 
Please feel free to open pull-request to update any version mentioned in that [.env](https://github.com/abdennour/dockerfiles/blob/master/.env) file.

**Comment by cw-sakamoto** [comment]
@marccarre @abdennour 
I'm sorry to send you a reply. Thank you for helpful advice!
