### ISSUE TITLE
Cluster update EndPoint

### ISSUE THREAD

**Issue by cdenneen** [weaveworks/eksctl#1558]
When you apply a `eksctl cluster update -f config.yaml` with updated Boolean for Private and Public endpoints.

**What you expected to happen?**
I would expect the update to be applied rather than having to run:

`eksctl utils update-cluster-endpoints --private-access=true --public-access=true`

**How to reproduce it?** (This does nothing with actually updating and appears as if it's already updated as desired)
```
% eksctl update cluster -f config.yaml --approve
[ℹ]  eksctl version 0.9.0
[ℹ]  using region us-east-1
[!]  NOTE: config file is used for finding cluster name and region
[!]  NOTE: cluster VPC (subnets, routing & NAT Gateway) configuration changes are not yet implemented
[ℹ]  re-building cluster stack "eksctl-shared-cluster"
[✔]  all resources in cluster stack "eksctl-shared-cluster" are up-to-date
[ℹ]  checking security group configuration for all nodegroups
[ℹ]  all nodegroups have up-to-date configuration
```

Include the steps to reproduce the bug

**Anything else we need to know?**
What OS are you using, are you using a downloaded binary or did you compile eksctl, what type of AWS credentials are you using (i.e. default/named profile, MFA) - please don't include actual credentials though!

**Versions**
Please paste in the output of these commands:
```
% eksctl version
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.9.0"}
% kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:24:29Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-eks-b7174d", GitCommit:"b7174db5ee0e30c94a0b9899c20ac980c0850fc8", GitTreeState:"clean", BuildDate:"2019-10-18T17:56:01Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
%
```

**Comment by martina-if** [comment]
Hi @cdenneen , thank you for raising this. I can see how it would be useful to have the `update` command apply different changes from the config file into the cluster. Today, this command is only meant to upgrade the control plane of the cluster. Perhaps we could make this more clear.

What you are defining is something like an `apply` command, similar to the one in `kubectl`. This has been considered as a future feature to implement [since some time ago](https://eksctl.io/community/roadmap/) but we haven't gotten to it. 

Since this is a particular use case of https://github.com/weaveworks/eksctl/issues/19 I will close this. But if you think there's something we should do in the short term like clarifying this in some part of the docs please feel free to reopen it.
