### ISSUE TITLE
private only access is broken

### ISSUE THREAD

**Issue by John-Vincent** [weaveworks/eksctl#1607]
**What happened?**
when I try to create a cluster with public access disabled eksctl fails with a warning message
"[✖]  warning, having public access disallowed will subsequently interfere with some features of eksctl. This will require running subsequent eksctl (and Kubernetes) commands/API calls from within the VPC.  Running these in the VPC requires making updates to some AWS resources.  See: https://docs.aws.amazon.com/eks/latest/userguide/cluster-endpoint.html#private-access for more details"

**What you expected to happen?**
I expect the deployment to attempt to continue anyway.

**Anything else we need to know?**
if you look at line 109 in https://github.com/weaveworks/eksctl/blob/master/pkg/apis/eksctl.io/v1alpha5/validation.go there seems to be a line that will cause this error to be returned always causing to program to exit

**Versions**
eksctl version 0.10.2
kubectl version lient Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

**Logs**
[ℹ]  eksctl version 0.10.2
[ℹ]  using region us-east-1                                                                                                           
[✖]  warning, having public access disallowed will subsequently interfere with some features of eksctl. This will require running subsequent eksctl (and Kubernetes) commands/API calls from within the VPC.  Running these in the VPC requires making updates to some AWS resources.  See: https://docs.aws.amazon.com/eks/latest/userguide/cluster-endpoint.html#private-access for more details

**Comment by KetsuN** [comment]
Any update/comment on this?  I'm having this same issue.  I would expect the creation to continue after the warning is raised.

**Comment by D3nn** [comment]
The issue here is that setting the public access to false means that we can no longer join the worker nodes to the cluster once the public access to the cluster is shut off.  It's possible to delay the enforcement of the access rules until after the nodes joined the cluster, but the next hurdle is that the ability to write the kubeconfig is subsequently also blocked.

We are looking at ways to work around that, but in the meantime, one can create the cluster with, e.g. public=true, private=true access and then, once the cluster has finished being created, update it with the command:

``` eksctl utils eksctl utils update-cluster-endpoints --name <cluster name> --public-access=false```

**Comment by martina-if** [comment]
I am closing this issue since this behavior is expected and documented here https://eksctl.io/usage/vpc-networking/#managing-access-to-the-kubernetes-api-server-endpoints
