### ISSUE TITLE
Support attachPolicyARNs for fargateProfile

### ISSUE THREAD

**Issue by inductor** [weaveworks/eksctl#1631]
**Why do you want this feature?**
This would be good especially when you want to use alb ingress with fargate just like how you deploy it with managed nodegroups.

**What feature/behavior/change do you want?**
fargateProfile supports attachPolicyARNs.

**Comment by jpadams** [comment]
@kalbir this might be related to what I was seeing where I can get to my LoadBalancer Service when I use

```
$ eksctl create cluster            # traditional EC2-backed
$ eksctl create cluster --managed  # managed node groups
```

but not for 

```
$ eksctl create cluster --fargate  # Fargate!
```

I have a programmatic user with this IAM policy (with AWS acct number filled in):
https://gist.github.com/jpadams/d1b076a6308346d581bc362360a858d0

And I'm using this GitHub action to do the build and deploy to the specified EKS cluster:
https://github.com/jpadams/fargate-eks/blob/master/.github/workflows/build-deploy.yml#L33

**Comment by inductor** [comment]
._.

**Comment by aclevername** [comment]
Thanks for opening the issue @inductor. Just too clarify, you want to be able to attach policy arns to `FargatePodExecutionRole` eksctl creates?

**Comment by inductor** [comment]
@aclevername I think I clarified what I originally wanted to do in the very first message, though it's a very long time ago...

**Comment by cPu1** [comment]
@inductor, the pod execution role that's passed to a Fargate profile is for giving the Fargate infrastructure access to the EKS cluster so that it can register with the cluster. Unlike node roles, the role specified for a Fargate profile's pod execution role cannot be assumed by the containers running in a Fargate pod. So even if eksctl attaches the policies, the Fargate pod still won't have the IAM permissions. The recommended way to give Fargate pods access to AWS resources is via IAM Roles for Service Accounts.

**Comment by cPu1** [comment]
> @inductor, the pod execution role that's passed to a Fargate profile is for giving the Fargate infrastructure access to the EKS cluster so that it can register with the cluster. Unlike node roles, the role specified for a Fargate profile's pod execution role cannot be assumed by the containers running in a Fargate pod. So even if eksctl attaches the policies, the Fargate pod still won't have the IAM permissions. The recommended way to give Fargate pods access to AWS resources is via IAM Roles for Service Accounts.

Closing the issue.
