### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by richardcase** [weaveworks/eksctl#166]
**Why do you want this feature?**
We need to improve the test coverage so that we have confidence in the effect of changes.

**What feature/behavior/change do you want?**
The test (unit tests) coverage should be increased. We should initially aim for around 60% coverage.

This is a follow on from #46 where we introduced the testing strategy.

**Comment by mumoshu** [comment]
@errordeveloper Could you enable codecov once again, so that we can better track deltas in the test coverage?

I see the codecov project is already there. But it seems to not have updated for months.

https://coveralls.io/github/weaveworks/eksctl?branch=master

**Comment by errordeveloper** [comment]
I'm not sure what broken, this needs to be looked into.

**Comment by errordeveloper** [comment]
I think we are in a better place now, but per-package coverage can be improved. I'm don't see a good reason to keep this issue open as is. I maybe a good idea to review the state of testing and open separate issue, otherwise I'm happy to just keep on improving every time one does work on the test suite.
