### ISSUE TITLE
Global Network LB for Multiple Nodeports

### ISSUE THREAD

**Issue by srinivasareddyasha** [weaveworks/eksctl#1735]
Hi am srinivasa I have a requirment Please suggest me the best solution................
We have EKS cluster in one region, there we are using multiple Load balancers for UDP and TCP requists But we need a single NLB for UDP. My main requirement is using Single NLB we have to route the services to multiple nodeports Please suggest me we have any option

**Comment by michaelbeaumont** [comment]
Hi, I don't think this issue is best answered at this repo. It seems more a general question of how best to integrate kubernetes with AWS services. You may be able to use `Ingress` to provision one load balancer and route traffic to several services.
Feel free to create a new issue if you have an `eksctl` specific question or need help.
