### ISSUE TITLE
`eksctl update cluster -f ` spits out `all resources are up-to-date` even if configuration file has changed

### ISSUE THREAD

**Issue by shunkakinoki** [weaveworks/eksctl#1936]
**What happened?**
After creating the cluster with eksctl,
updating the cluster doesn't work even after changing the configuration yaml

**What you expected to happen?**
`eksctl update cluster -f <filename>` should update cluster to reflect the change on the configuration yaml

**How to reproduce it?**
Tried deleting and recreating the clusters but update doesn't work

**Anything else we need to know?**
What OS are you using, are you using a downloaded binary or did you compile eksctl, what type of AWS credentials are you using (i.e. default/named profile, MFA) - please don't include actual credentials though!

macOS Catalina
named profile
CLIs all installed with brew

**Versions**
Please paste in the output of these commands:
```
$ eksctl version = 0.14.0
$ kubectl version = Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-13T18:07:54Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
```

**Logs**
Include the output of the command line when running eksctl. If possible, eksctl should be run with debug logs. For example:

[ℹ]  eksctl version 0.14.0
[ℹ]  using region us-east-1
[!]  NOTE: config file is used for finding cluster name and region
[!]  NOTE: cluster VPC (subnets, routing & NAT Gateway) configuration changes are not yet implemented
[ℹ]  re-building cluster stack "api-beta-cluster"
[✔]  all resources in cluster stack "api-beta-cluster" are up-to-date
[ℹ]  checking security group configuration for all nodegroups
[ℹ]  all nodegroups have up-to-date configuration

**Comment by martina-if** [comment]
Hi @shunkakinoki , thank you for reporting this. I think the update command is a little misleading.

The eksctl update cluster command, doesn't work like kubectl update. This command is used to upgrade the control plane to the next kubernetes version, and update the stacks if needed, but it doesn't modify the properties of the cluster.

I created [an issue](https://github.com/weaveworks/eksctl/issues/1955) to improve the command's documentation so that this doesn't confuse other users (which has done a lot!).

I will close this issue but if you think there's something we haven't considered please feel free to reopen it.

**Comment by shunkakinoki** [comment]
@martina-if
Appreciate the work!

Thanks for clarifying up my point on the new issue.

So based on my understanding, there are no commands currently that works like ‘kubectl update’ for eksctl?

**Comment by martina-if** [comment]
No, not at the moment. We do have [this issue](https://github.com/weaveworks/eksctl/issues/462) and #19 so at some point we hope there will be something like that.

There are other subcommands though that can perform certain modifications, most of them under the `eksctl utils` command.
