### ISSUE TITLE
`eksctl create nodegroup` attempts to modify cluster stack even when it's not required

### ISSUE THREAD

**Issue by cPu1** [weaveworks/eksctl#1991]
**What happened?**
`eksctl create nodegroup` on a cluster that doesn't use Fargate results in an update of the cluster stack. While the stack update doesn't add the resources required for Fargate, eksctl should not attempt to update the cluster stack.

**What you expected to happen?**
For the cluster stack to not be updated when Fargate profiles aren't being used.

**How to reproduce it?**
Create a cluster with no Fargate profiles. This will ensure the resources for Fargate (FargatePodExecutionRoleARN) aren't added to the cluster stack. Then a subsequent `eksctl create nodegroup` will detect that the resources for Fargate are missing and attempt to update the stack. 

```shell
$ eksctl create cluster
$ eksctl create nodegroup
```

**Versions**
```
$ eksctl version
0.15.0
```

**Logs**
```shell
$ eksctl create nodegroup -f config.yaml
[ℹ]  will create a CloudFormation stack for each of 1 nodegroups in cluster "ng-test"
[ℹ]  2 sequential tasks: { fix cluster compatibility, 1 task: { 1 task: { create nodegroup "ng-1" } } }
[ℹ]  checking cluster stack for missing resources
[ℹ]  cluster stack is missing resources for Fargate
[ℹ]  adding missing resources to cluster stack
```

**Comment by agbanagba** [comment]
This happens in the cluster compatibility test for both managed nodes and fargate. The current situation assumes that when there is no **FargatePodExecutionRoleARN** in the cloudformation cluster stack output, it does not support fargate and tries to update the cluster stack to add the appropriate role which does not actually update because there are no fargate profiles in the cluster config.

https://github.com/weaveworks/eksctl/blob/66741958e0389ea36f40eebd8b26c18144cd75ff/pkg/cfn/manager/compat.go#L56-L72
