### ISSUE TITLE
Cluster API controller

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#20]
We would like to implement [Cluster API](https://github.com/kubernetes-sigs/cluster-api). One of the modes in which one can use Cluster API is by having a management cluster which runs a controller (actuator), which creates new clusters and nodegroups when it receives Cluster API objects.
Another mode of using it would be via CLI (#19).

**Comment by jicowan** [comment]
@errordeveloper wondering if you've seen this project yet, https://github.com/awslabs/aws-eks-cluster-controller.

**Comment by errordeveloper** [comment]
Hi @jicowan, yes, it did come up. Thanks for bring it up, there appears to be an overlap. It would be great to see if we can join efforts, if the team behind the project intends to ramp up development.

**Comment by k** [comment]
Whats going on with this? It appears that development is still going on in https://github.com/awslabs/aws-eks-cluster-controller but this issue isn't closed?

**Comment by marccarre** [comment]
We still plan to make `eksctl` support the cluster API, however this work hasn't been prioritised yet. Also, the user experience will most likely be different from `awslabs/aws-eks-cluster-controller`'s, as we'd like it to be [GitOps](https://github.com/weaveworks/awesome-gitops/blob/master/README.md)-friendly. We'll update this issue as the situation evolves.

**Comment by dcherman** [comment]
Out of curiosity, has there been any progress in making that internal PoC that WeaveWorks has open source?  Or has that effort stalled pending remaining work for this issue?

**Comment by michaelbeaumont** [comment]
@dcherman I'd love to hear your thoughts on `eksctl` and [the Cluster API AWS provider](https://github.com/kubernetes-sigs/cluster-api-provider-aws/).

**Comment by dcherman** [comment]
@michaelbeaumont Are you asking me if you should try to implement a Cluster API Provider, or what my thoughts are on the experimental EKS support in the Cluster API AWS Provider?

If it's the former, then absolutely yes.  While Cluster API itself is relatively young, I think a significant amount of tooling will be built around it as it matures.  If we implement a provider that works with Cluster API, then we will likely be able to take advantage of that work.

If it's the latter, then I think my answer would be that it's super exciting to see work being done in this area.  Crossplane is another example to look at (and is what I'm currently experimenting with since it's more mature).  One possible thought would be to contribute something to cluster-api-aws that implements their EKS support on top of the work that eksctl has already done, although eksctl itself provisions quite a bit more infrastructure than just k8s/nodes if I recall correctly (haven't used it in a bit admittedly!)

**Comment by joebowbeer** [comment]
I'm here trying to figure out what GitOps tools I should use going forward for EKS cluster config, especially with ClusterAPI on the horizon.

Specifically, I'm wondering about `eksctl` vs `clusterctl --flavor eks` and about the eksctl quickstart profile vs the clusterctl capi-eks-quickstart template. Maybe a ClusterAPI controller will be a factor, too.

Neither the eksctl getting started docs nor the roadmap provide much insight.

**Comment by rverma-nsl** [comment]
@joebowbeer Just wondering did you made a decision yet, we are facing same dilemma  :)

**Comment by nikimanoledaki** [comment]
Closing this issue in favour of [CAPA](https://github.com/kubernetes-sigs/cluster-api-provider-aws) which should be used for doing this kind of cluster creation.
