### ISSUE TITLE
eksctl 0.17 comes w/ CNI 1.5.7 instead of 1.6.0

### ISSUE THREAD

**Issue by RobertLucian** [weaveworks/eksctl#2049]
Per @sayboras' recommendation, I created a ticket. Thanks!

**What happened?**

Looking at [aws-node.yaml](https://github.com/weaveworks/eksctl/blob/0.17.0/pkg/addons/default/assets/aws-node.yaml#L90), tagged with version *0.17*, one can notice that the default version of `602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni:v1.6.0` is *1.6*, which is the expected version to get, but unfortunately, I'm getting version *1.5.7* when creating the cluster.

**What you expected to happen?**
Getting version *1.6.0* of CNI instead of *1.5.7* on version *0.17* of `eksctl`. Version 1.6.0 of CNI is required for `Inf` instances.

**How to reproduce it?**
Create an `eksctl` cluster with version *0.17* and then run `kubectl describe daemonset aws-node --namespace kube-system | grep Image | cut -d "/" -f 2`. The retrieved image version is `amazon-k8s-cni:v1.5.7` instead of `amazon-k8s-cni:v1.6.0`.

**Good to know**

* https://github.com/weaveworks/eksctl/pull/1824
* https://github.com/weaveworks/eksctl/blob/master/pkg/ctl/utils/update_aws_node.go#L16

**Comment by sayboras** [comment]
@RobertLucian thanks for creating this issue. During cluster creation, CNI version will be defaulted as 1.5.7 as for per official AWS [docs](https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html).

If you are using eksctl 0.17.0 version, you can run `eksctl utils update-aws-node` to update to CNI 1.6.0 post cluster creation.

@martina-if @cPu1 just want to need your input on expected behavior of `eksctl utils update-aws-node`. 

Currently, default CNI version is _1.5.7_ [docs](https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html), and the lastest CNI version is _1.6.0_ as per [docs](https://aws.amazon.com/about-aws/whats-new/2020/02/amazon-eks-announces-release-of-vpc-cni-version-1-6/), will this command update to:

- latest default version. This is helpful in case of EKS version upgrade or there is change to default CNI version like from 1.5.5 to 1.5.7) or 
- lastest CNI semantic version (e.g. 1.6.0)

**Comment by martina-if** [comment]
Thanks @sayboras,

The current behavior of the `utils update-aws-node` command is to update to the latest version (the latest known by eksctl). There are no plans to support multiple ones at the moment.
