### ISSUE TITLE
Wish to add support defining managedNodeGroups.launchTemplate from cli

### ISSUE THREAD

**Issue by nixilin** [weaveworks/eksctl#2600]
**Why do you want this feature?**
I see that specify managedNodeGroups.launchTemplate.id and managedNodeGroupslaunchTemplate.version is supported from 0.26.0. But it only be set from yaml.

**What feature/behavior/change do you want?**
Setting managedNodeGroups.launchTemplate[id,version] from cli.  Just like we set node instance type via --node-type=t3.xlarge

Do not hesitate, when appropriate, to share the exact commands or API you would like, and/or to share a diagram (e.g.: asciiflow.com): "a picture is worth a thousand words".
define launchTemplate related para like the following style:
eksctl create ng --cluster=EKS-LAB --region=ap-northeast-1 --node-type=t3.xlarge --launchTemplate-id=lt-0d2d271a6c9e8fe17 --launchTemplate-version=2

**Comment by cPu1** [comment]
Hi @nixilin,
For complex configuration, like setting the launch template ID, we recommend using a config file, rather than the CLI options. The CLI options exist to quickly stand up a single-nodegroup cluster. However, if we get more requests for adding launch template support via CLI options, we may consider adding it.
