### ISSUE TITLE
Update docs for new aws-load-balancer-controller

### ISSUE THREAD

**Issue by michaelbeaumont** [weaveworks/eksctl#2770]
**Why do you want this feature?**
`aws-alb-ingress-controller` is now `aws-load-balancer-controller`, make sure our docs mention it and [how to use it](https://kubernetes-sigs.github.io/aws-load-balancer-controller/guide/controller/installation/) with `eksctl`.

**What feature/behavior/change do you want?**
Docs updates/potentially deprecate `withAddonPolicies.albIngress`.

**Comment by Callisto13** [comment]
As part of this I have updated the [app-dev quickstart profile](https://github.com/weaveworks/eks-quickstart-app-dev) to deploy the new AWS Load Balancer Controller, as well as the policy created when `spec.albIngress` is set (the old one works anyway, but it is nice to have new things).

I have updated all mentions of the ALB in our docs, although they were few to begin with, and pointed to the [AWS documentation](https://docs.aws.amazon.com/eks/latest/userguide/alb-ingress.html).

**Some thoughts:**

- When using a quickstart profile, `spec.albIngress` (which I have not renamed yet in case it breaks things) is still useful since it will automate the policy creation, so I have not deprecated this.
- However, this option is not necessary when deploying the controller outside of a profile. The docs provided by amazon are accurate and thorough and it would be weird (and just generally not good) to duplicate half of them here when paired with `spec.albIngress` (which you can still use in your own combination of deployment flow if you like).
- The AWS LBC docs detail an IRSA setup which does not line up with how we currently do addon policies: eksctl creates inline policies on the role, which cannot be attached anywhere else, say as part of a `create iamserviceaccount` call. There is an issue already open (https://github.com/weaveworks/eksctl/issues/2837) to do IRSA addon policies, so we will get around to making this happen for the LBC eventually.

**Question:**

For all the people watching this issue: what sort of documentation would you like to see? Is there anything in the [AWS doc](https://docs.aws.amazon.com/eks/latest/userguide/alb-ingress.html) which is not clear?
