### ISSUE TITLE
Document how to add tags to nodegroups

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/eksctl#2876]
See thread [here](https://weave-community.slack.com/archives/CAYBZBWGL/p1606330312304100).

> David Nov 25th at 7:51 PM
Hi guys. Is it possible to add custom tag on nodes during cluster creation, please? :crossed_fingers: I tried few things and went through your docs and I did't find it find solution :(
4 replies

> chetan:weaveworks:  4 days ago
This is supported via the tags field on a nodegroup or managedNodeGroup
```
managedNodeGroups:
- name: ng
  tags:
    tag1: value1
```

> David  4 days ago
@chetan this tags the node group and not node itself (ec2 instance), right?

> chetan:weaveworks:  4 days ago
It tags both the managed nodegroup resource in EKS and the EC2 instances, but not the ASG

> David  4 days ago
Cool. You are right. Thank you :bow:

**Comment by tkms0106** [comment]
I'd like to work on this.
Should I modify `pkg/apis/eksctl.io/v1alpha5/assets/schema.json` ?

**Comment by tkms0106** [comment]
It seems I shoud edit `pkg/apis/eksctl.io/v1alpha5/types.go` .

**Comment by Callisto13** [comment]
Awesome! All yours @tkms0106 👍 .

Yep, editing `pkg/apis/eksctl.io/v1alpha5/types.go` (and running `make generate-all` after), will update the schema docs. You can also find the relevant section in `userdocs/src/usage/` if you want to add a little more detail. There is a small section about serving the docs locally in the [contributing guide](https://github.com/weaveworks/eksctl/blob/master/CONTRIBUTING.md#building-eksctl).

**Comment by michaelbeaumont** [comment]
@tkms0106 Note that the possibilities for showing usage of `tags` in the schema, which show up at [/usage/schema](https://eksctl.io/usage/schema/#nodeGroups-tags) are pretty limited so I suggest adding something to the docs like @Callisto13 suggested

**Comment by tkms0106** [comment]
@Callisto13 @michaelbeaumont Oh I didn't notice that point because I always read "[Config file schema](https://eksctl.io/usage/schema/)" page first, recently.

And I found that the description of tagging is already in "[EKS Managed Nodegroups](https://eksctl.io/usage/eks-managed-nodes/#feature-parity-with-unmanaged-nodegroups)" page.

https://github.com/weaveworks/eksctl/blob/9e00123896fa31493b6170f41f56cb688527105a/userdocs/src/usage/eks-managed-nodes.md#L219-L220

Hmm should we think this issue is already resolved?

Anyway I'd like to add some comment on `types.go` as I was thinking first.

**Comment by michaelbeaumont** [comment]
Sure, go for it!

**Comment by aclevername** [comment]
Closed by #3204
