### ISSUE TITLE
Updating nodegroup subnets

### ISSUE THREAD

**Issue by patstrom** [weaveworks/eksctl#3191]
Hello! Our subnets have started to run out of IP addresses so I have created some new subnets, tagged them accordingly and 
now I want to update the cluster config file so that existing nodegroups start using the new subnets as well. Is this possible? Or do I need to create completely new nodegroups?

Also, how would I go about updating the `vpc` config for the smoothest experience? Currently it looks like this:

```
vpc:
  subnets:
    private:
      eu-west-1a:
        id: "subnet-"
      eu-west-1b:
        id: "subnet-"
      eu-west-1c:
        id: "subnet-"
    public:
      eu-west-1a:
        id: "subnet-"
      eu-west-1b:
        id: "subnet-"
      eu-west-1c:
        id: "subnet-"
```

and I want to add 3 new subnets (one in each AZ) for `private` networking use. Can I provide more subnets under each AZ key or do I need to create completely new keys for the new subnets? If the latter is the case, what is the default behavior when creating new nodegroups? Will they only use the one with the AZ keys by default?

I didn't find anything explicit about this in the documentation so I just want to clarify.

Thanks in advance!

**Comment by Callisto13** [comment]
Hey @patstrom, thanks for asking!

Our ability to update existing nodegroups is extremely limited currently, so you would indeed have to delete your existing nodegroups an create new ones in your new subnets. (@aclevername can correct me if I am wrong about this).

As for detailing your new subnets in the spec, we recently improved this area of the spec so that you can provide arbitrary keys in that object. See the docs [here](https://eksctl.io/usage/vpc-networking/#custom-subnet-topology), and the example config [here](https://github.com/weaveworks/eksctl/blob/main/examples/24-nodegroup-subnets.yaml).

**Comment by patstrom** [comment]
Hey!

How does the arbitrary keys work with default subnets? Right now (with the subnet config in the OP) I do not specify a subnet at all for the nodegroups. If I were to replace the current subnets with the new one and then use `eksctl create nodegroup` (while also renaming the nodegroups, of course) would that work?

When exactly is the `vpc.subnets` config used? Only locally and when creating nodegroups? Or is it stored somewhere in CloudFormation or via tags?

**Comment by aclevername** [comment]
Hey @patstrom 

 
> How does the arbitrary keys work with default subnets? Right now (with the subnet config in the OP) I do not specify a subnet at all for the nodegroups.

By default the nodegroups are assigned to use all of the public subnets provided. You can choose to limit a nodegroup to a set subnets or an AZ under the nodegroup configuration, [docs](https://eksctl.io/usage/vpc-networking/#use-existing-vpc-other-custom-configuration). For example:

```
vpc:
  id: "vpc-11111"
  subnets:
    public:
      private-one:
          id: "subnet-0153e560b3129a696"
    ... # subnet spec continued

nodeGroups:
  - name: ng-1
    instanceType: m5.xlarge
    desiredCapacity: 2
    privateNetworking: true
    subnets:
      - private-one
 ```

>  If I were to replace the current subnets with the new one and then use `eksctl create nodegroup` (while also renaming the nodegroups, of course) would that work?

I don't believe so. Looking at a nodegroup I've created it uses the cluster cloudformation stack to reference the subnets:
```
    "NodeGroup": {
      "Type": "AWS::AutoScaling::AutoScalingGroup",
      "Properties": {
        ...
        "VPCZoneIdentifier": {
          "Fn::Split": [
            ",",
            {
              "Fn::ImportValue": "eksctl-jk-cluster::SubnetsPublic"
            }
          ]
        }
      },
 ```

> When exactly is the `vpc.subnets` config used? Only locally and when creating nodegroups? Or is it stored somewhere in CloudFormation or via tags?

The VPC configuration is used to create the cluster,  and the nodegroup as described above. The output is stored in the cloudformation stack.

> I.e. go from
> 
> ```
> vpc:
>   subnets:
>     private:
>       eu-west-1a:
>         id: "subnet-old"
>       eu-west-1b:
>         id: "subnet-old"
>       eu-west-1c:
>         id: "subnet-old"
> 
> nodeGroups:
>   - name: magnificent-shrimpsallad-118
>     instanceType: m5.large
>     minSize: 1
>     maxSize: 20
>     privateNetworking: true
> ```
> 
> to
> 
> ```
> vpc:
>   subnets:
>     private:
>       eu-west-1a:
>         id: "subnet-new"
>       eu-west-1b:
>         id: "subnet-new"
>       eu-west-1c:
>         id: "subnet-new"
> 
> nodeGroups:
>   - name: magnificent-shrimpsallad-118-new
>     instanceType: m5.large
>     minSize: 1
>     maxSize: 20
>     privateNetworking: true
> ```
> 
> and then just essentially do `eksctl create nodegroups -f cluster.yaml` eventually followed by `eksctl delete nodegroup -f cluster --only-missing`?

I don't believe this will work. I'm not entirely sure on how to suggest you should proceed, from my understanding once an EKS cluster is created with subnet X, Y and Z it cannot be changed. Eksctl then always uses X/Y/Z to create nodegroups in. I could be wrong, @michaelbeaumont might have more context

**Comment by patstrom** [comment]
Alright, that is quite troubling for my situation.

Do note that the VPC itself is not managed by eksctl. I have re-used an existing one. Nor has it created the any of these subnets. I can see that it has specified the `SubnetsPrivate` "variable" in CloudFormation though.

So how would I go about updating the subnets? I suppose I could do with just adding more subnets to the existing list but it sounds like that isn't really supported either? I would prefer not to have to re-create the entire cluster.

If I were to manually update the CloudFormation stack and change the `SubnetsPrivate` output into the desired ones, how would that work?

**Comment by michaelbeaumont** [comment]
Unfortunately you can't update the subnets registered with the cluster. https://github.com/aws/containers-roadmap/issues/170 is tracking that. Some comments there https://github.com/aws/containers-roadmap/issues/170#issuecomment-469371567 suggest that it's possible to launch nodes in subnets not registered with the cluster but it may be a bit of a hassle to have it work correctly.

@aclevername is correct in that currently `eksctl` uses the subnets from the cluster stack to create nodegroups so that'd be the next blocker. You'd be able to just edit the cluster stack outputs `SubnetsPublic`/`SubnetsPrivate` though.

**Comment by patstrom** [comment]
> You'd be able to just edit the cluster stack outputs SubnetsPublic/SubnetsPrivate though.

And manually editing those will actually work? And not break something unexpected?

**Comment by michaelbeaumont** [comment]
I'm pretty sure it will work _assuming_ you get past the general issues around using nodes in subnets the _cluster_ isn't using as discussed in the containers-roadmap issue, which I am definitely not sure will work and have no experience with. Changing the CFN stack will only get around the `eksctl` issue with using subnets the _stack_ doesn't know about. I.e. even if the containers-roadmap issue was suddenly solved and you could update the cluster subnets, you'd still have to edit the cloudformation stack outputs right now.

**Comment by patstrom** [comment]
Alright, thank you for the assistance!

**Comment by patstrom** [comment]
@michaelbeaumont I saw that you recently merged https://github.com/weaveworks/eksctl/pull/3331.

From reading up on EKS networking (and especially the links in [this comment](https://github.com/aws/containers-roadmap/issues/170#issuecomment-780174859) it looks like simply specifying the explicit subnet id when creating the new nodegroups should be fine (and thus bypassing having to manually edit the cluster CFN stack). Is that PR part of the latest release?

**Comment by Callisto13** [comment]
@patstrom I can confirm that the PR was released in [`0.40.0`](https://github.com/weaveworks/eksctl/releases/tag/0.40.0) 👍

**Comment by michaelbeaumont** [comment]
@patstrom I don't _think_ that PR allows you to do what you need yet.
Even with that PR, `eksctl` still looks for the IDs in the subnets taken from the stack (or from the `.vpc` field for non-eksctl clusters).

The final step here would be to simply be more permissive with `.subnets`:

1. like we do now, check if the string `.subnets[i]` is a key in `clusterConfig.vpc.subnets.{private,public}` (the case when it's specified in the config under `.vpc` or loaded from the stack)
1. like we do now, check if the string is the `ID` of a subnet in `clusterConfig.vpc.subnets.{private,public}` (what that PR allowed)
1. if that all fails, just use the string as the subnetID

It may be enough to change:
https://github.com/weaveworks/eksctl/blob/2a79dd0c59ae69346734cbbc71aea6a1823950d6/pkg/vpc/vpc.go#L588-L591
to something like 

```
		if subnetID == "" {
                        subnetID = subnetName
			logger.Info("Using non-control plane subnet %s", subnetName)
		}
                subnetIDs = append(subnetIDs, subnetID)
```

but it might be useful to check if the subnet actually exists as well. Some other code may very well depend on having that subnet in `vpc.subnets` so this may not be enough.


As an aside, it may also be worth adding tests that `vpc.UseFromClusterStack` does not ignore or remove subnets that aren't found in the stack outputs from `ClusterConfig.vpc.subnets` if they were specified there in the config file, otherwise using non-control plane subnets won't work in case 1).

**Comment by patstrom** [comment]
Perhaps it would be worthwhile to create a separate issue about this?

It seems AWS now quite explicitly recommends running nodegroups in subnets that _aren't_  defined when creating the EKS cluster and eksctl should probably have better and more intuitive support for that.

I suppose it would be quite nice to allow some kind of "free-form" subnet ids (as you suggested) as well as perhaps making a distinction between `vpc.subnets` and a simple `subnets` in the config file. Perhaps something like

```yaml
vpc:
  # These are the cluster subnets and should essentially only support EKS managed ENIs. I.e. be `/29` masked and not necessarily manually managed at all.
  subnets:
    private:
      private-one:
        id: whatever
    
# These are the subnets you should run your nodegroups in. They should be separate from the cluster subnets.
nodeGroupSubnets:
  private:
    private-one:
      id: whatever
  # These are the ones we launch loadbalancers in
  public:
    public-one:
      id: whatever
```

Or at least that's how I understand the [recommendations](https://docs.aws.amazon.com/eks/latest/userguide/network_reqs.html). The reason for adding them to eksctl would be to have the necessary tagging happening automatically.

I guess the heart of the issue here is that it seems that the subnets specified during cluster creation are fundamentally different in their usage from subnets that loadbalancers and nodes are launched in, and thus it might be worthwhile to separate them during configuration?
