### ISSUE TITLE
Mac Instance for node

### ISSUE THREAD

**Issue by shinji62** [weaveworks/eksctl#3237]
**What help do you need?**

I just want to know if people are using group node with mac1.metal instance, or  if EKS support mac instances

**Comment by Callisto13** [comment]
Hi @shinji62 thanks for asking.

As far as I know, EKS does not support mac instances (and I believe mac EC2 instances are only supported in a couple of regions). I am not sure what plans AWS has for mac instances on EKS, but since mac instances are _very_ expensive to run, and since native mac OS containers are not really a "thing" (they are just linux containers running in a Hyve VM), having an EKS cluster running with mac OS nodes feels weird to me 🤷‍♀️ .

**Comment by Callisto13** [comment]
Gonna close this now, if you want more details on this I suggest asking in https://github.com/aws/containers-roadmap
