### ISSUE TITLE
cli: Invalid images are accepted.

### ISSUE THREAD

**Issue by joshti** [weaveworks/eksctl#3405]
**What were you trying to accomplish?**
Tried to deploy a cluster with Bottlerocket.

**What happened?**
AL2 deployed instead.

**How to reproduce it?**
`eksctl create nodegroup --cluster my-favourite-cluster --node-type t3.medium --node-ami Calcium --max-pods-per-node 100 --ssh-access`

**Anything else we need to know?**
There isn't a node-ami with the id of `Calcium`. `Bottlerocket` reproduces the same issue, but I'm assuming this could change with time. `node-ami-family` works as expected with `Bottlerocket`, but I believe doesn't error out either.

**Versions**

```
[cloudshell-user@ip-10-0-104-110 ~]$ eksctl version
0.37.0
```

**Comment by cPu1** [comment]
Thanks for reporting this issue. This is indeed a bug in eksctl as it's not disallowing invalid AMI values, and a confusing behaviour because it defaults to using SSM parameters to resolve the AMI. A [PR](https://github.com/weaveworks/eksctl/pull/3412) has been opened to fix the issue, it will be out in the next release.

**Comment by joshti** [comment]
Thanks much 😸
