### ISSUE TITLE
publish eksctl snap on snapstore

### ISSUE THREAD

**Issue by toabctl** [weaveworks/eksctl#3436]
There is already a snap build directory. It would be nice if the snap could be build and published automatically on the https://snapcraft.io/#

**Comment by Callisto13** [comment]
Hi @toabctl, we used to have a snap on snapcraft, but the team decided to stop releasing snaps about a year ago as it was too much work to maintain.

**Comment by toabctl** [comment]
Hm. ok. Any hints what actually was too much work? I wonder if something like that couldn't be automated with github actions .

**Comment by Callisto13** [comment]
This is a little before my time, but it looks like the snap (and work around setting up CD) was disabled in January 2020 (https://github.com/weaveworks/eksctl/issues/215#issuecomment-580780317) while waiting for fixes for https://github.com/weaveworks/eksctl/issues/1721 and some "other issues" (unspecified). Perhaps @dholbach has more context?

We have not looked at this since then as it ceased to be a priority for the team,

**Comment by dholbach** [comment]
@Callisto13 IIRC It was deemed less of a priority and that there might be testing overhead if we'd publish several binaries / output formats.

**Comment by dholbach** [comment]
(Oh and hi @toabctl ! Good to see you again! :grinning: )

**Comment by toabctl** [comment]
Hey @dholbach :)
would you accept patches to fix the snap build and do snap builds as part of a PR so at least the build is not breaking again?

**Comment by aclevername** [comment]
Thanks for bumping the issue @toabctl , we will discuss bringing this back in this weeks planning and get back to you :smile:

**Comment by Callisto13** [comment]
Hi @toabctl thanks for your patience on this.

The team does not currently have capacity to prioritise this at the moment, in a couple of months there will be more of us so we will be able to revisit then.

In the meantime, we would be happy to consider PRs to handle things which do not require credential-led access to things 😄 .
