### ISSUE TITLE
Scale down specific nodes and decrement desired capacity

### ISSUE THREAD

**Issue by thanhma** [weaveworks/eksctl#3813]
**What feature/behavior/change do you want?**

Can we have a feature to scale down a nodegroup by specify instance ID(s), and also decrement the desired capacity of the corresponding ASG.

This could be familiar to the [Detach ](https://docs.aws.amazon.com/autoscaling/ec2/userguide/detach-instance-asg.html)feature of ASG, which will remove the instance(s) from ASG, plus termination for these instances.

Somethings like this: 
```bash
eksctl scale ng --cluster my-cluster --name my-ng --scale-down-nodes i-abcde12345,i-efghi67899
```
will remove two instances from `my-ng` nodegroup and decrement desired capacity by 2.

**Why do you want this feature?**

There are times we want to scale down a nodegroup and expect the nodes with the least pod scheduled to be removed, but current scale down seems to use Default termination policy, that may result in termination of nodes with plenty of pods. This could make the scale down longer, and higher chance of service interruption due to pod recreation.

If we can specify which node(s) to be removed, we can control the termination and prevent unexpected behavior when rescheduling pods.

**Comment by Callisto13** [comment]
Hi @thanhma thanks for asking, the team will have a chat about this request and get back to you 👍 .

If in the meantime feel free to PR something, even just a POC 😄

**Comment by Skarlso** [comment]
Hello!

This sounds like a specific issue based on scheduling and pod propagation in a Kubernetes cluster. If you would like to remove a specific node, cordon it, then remove it, then scale down the nodegroup.

Also, this problem is too specific to create an eksctl command for. Plus doing a specific node cordon and scale down from eksctl is problematic and error prone due to the removal of workloads and balancing pods which is something that should be done via supervision.
