### ISSUE TITLE
--wait=false does not work when upgrading nodegroups

### ISSUE THREAD

**Issue by connorearl** [weaveworks/eksctl#3889]
When using eksctl 0.54.0 to update a managed node group from 1.19 to 1.20, the --wait=false flag still causes the command to wait for CloudFormation.

When using the --timeout flag that will make it only wait for the time specified, but the exit code is 1, causing it to fail any scripts I use the command in.

This is the command I used:
`eksctl upgrade nodegroup --cluster cluster-name --name=nodegroup-name --wait=false --kubernetes-version=1.20`

**Comment by aclevername** [comment]
Definitely a bug, thanks. Looks like the value of `--wait` gets ignored.

**Comment by Skarlso** [comment]
For managed nodegroups, the stack also needs to be upgraded, before upgrading the actual nodegroup. Which means, there is no way to not wait for that, otherwise, the upgrade will not work.

What we could skip is the last stack update wait. I'm not sure if that is enough?

**Comment by kr3cj** [comment]
Thanks for the explanation @Skarlso. For anyone finding this issue in the future, we decided to just emulate what the EKS console does (since it doesn't wait which is what we want). One can just call the [UpdateNodegroupVersion](https://docs.aws.amazon.com/eks/latest/APIReference/API_UpdateNodegroupVersion.html) command and provide nodegroupName, releaseVersion, and name. We will do this from our homegrown wrapper tool around EKS.
