### ISSUE TITLE
Don't overload '--ssh-public-key' and allow bootstrapping multiple public key files

### ISSUE THREAD

**Issue by whereisaaron** [weaveworks/eksctl#391]
I think it would be cleaner to have '--ssh-public-key-name' for AWS Key Pairs and '--ssh-public-key-file' for local files, rather than overload two mechanisms onto '--ssh-public-key'?

I know AWS only lets you launch with one key, but `etcctl` could potentially allow `--ssh-public-key-file` multiple times and bootstrap in userdata an `authorized_keys` file to be appended to any AWS-installed public key.

```
etcctl --ssh-access [...]

etcctl --ssh-public-key-file=~/.ssh/id_rsa.pub [...]

etcctl --ssh-access --ssh-public-key-name=my-aws-key-pair [...]

etcctl --ssh-public-key-file=~/.ssh/id_rsa.pub \
  --ssh-public-key-file=project/project_ssh.pub \
  --ssh-public-key-name=my-aws-key-pair`
```

`--ssh-access` doesn't really say what it does, `--ssh-my-public-key` would be clearer, but it may be easier to not make a breaking option change.

```
etcctl --ssh-my-public-key --ssh-public-key-name=my-aws-key-pair [...]
```

**Comment by errordeveloper** [comment]
@whereisaaron interesting idea, thank you. I would rather avoid adding to many flags, as we have config file support underway (#381). So far as the API is concerned, the struct already has path, key name and body as separate fields. The struct clearly is in need of some refactoring (#386), so there is an opportunity to consider best way going forward.
So here is my suggestion:
- keep the behaviours of CLI flags as is
- improve structure of the API, e.g. move into a struct that is a pointer, maybe get rid of the boolean flag
- add multi-key support

We should also discuss #237 a little more, because that sounds potentially more useful than SSH statically provisioned SSH keys, but I'm not very familiar with SSM agent in practice.

**Comment by whereisaaron** [comment]
Great, looking forward to a config file.

The ideal is no ssh access; We shouldn’t need to get on nodes at all. So I agree wedon’t need to focus on this or have complicated features.

Nodes should be 100% disposable. I guess SSM might allow quick security updates until the updated AMI is available.

**Comment by errordeveloper** [comment]
Closing as config file now allows for 3 options that let's you either import a key, or use an existing EC2 key (`ssh.{publicKeyName,publicKeyPath,publicKey}`, see #713).
