### ISSUE TITLE
1.21 upgrade - kube-proxy invalid/old image tag

### ISSUE THREAD

**Issue by cwwarren** [weaveworks/eksctl#4003]
**What were you trying to accomplish?**
I upgraded a test cluster to 1.21 using eksctl.

**What happened?**
After running update-kube-proxy the image tag was `1.21.2+<gitsha>-eksbuild.1`.

That tag is invalid, when switched to `1.21.2-eksbuild.1` (note the `.1`) it does not support `arm64`.

**How to reproduce it?**
`eksctl utils update-kube-proxy` on EKS 1.21

**Anything else we need to know?**
https://docs.aws.amazon.com/eks/latest/userguide/managing-kube-proxy.html#kube-proxy-versions

`1.21.2-eksbuild.1` is broken on `arm64`

The latest `1.21.2-eksbuild.2` appears to be working successfully everywhere.

**Versions**
eksctl 0.58.0-rc0

**Comment by Callisto13** [comment]
Thanks for reporting @cwwarren 👍 

> `1.21.2+<gitsha>-eksbuild.1`

That sha is... odd.

> `1.21.2-eksbuild.1` is broken on `arm64`

🤦‍♀️ that's annoying

> The latest `1.21.2-eksbuild.2` appears to be working successfully everywhere.

Good to know 👍 

How was the `kube-proxy` initially added to your cluster? Did you:
a) use the addon api the cluster config or run `eksctl create addon`, or 
b) do nothing, it just was there as part of cluster create

**Comment by Callisto13** [comment]
I have reproduced (with option `b`) and there is definitely something off about that sha in the image id. I was able to get the proxy to stop erroring with

```
Warning  InspectFailed  4m51s (x50 over 14m)  kubelet            Failed to apply default image tag "602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/kube-proxy:v1.21.2+d2965f0db10712-eksbuild.1": couldn't parse image reference "602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/kube-proxy:v1.21.2+d2965f0db10712-eksbuild.1": invalid reference format
```

by editing the daemonset:

```bash
kubectl edit daemonset/kube-proxy -n kube-system
```
```yaml
# in the file changing
image: 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/kube-proxy:v1.21.2+d2965f0db10712-eksbuild.1

# to
image: 602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/kube-proxy:v1.21.2-eksbuild.1
```

The proxy pods then started running.

-------------------

I am not sure where that sha is coming from , so still need to look into that, but for now the above workaround should help.

I still need to look into the arm issue and decide whether we should just always go for build.2 for versions above 18.

**Comment by cwwarren** [comment]
This cluster in particular dates back to EKS 1.17 and `kube-proxy` was there as part of cluster create. `eksctl utils update-kube-proxy` was used to upgrade `kube-proxy` after every major version upgrade: 1.17 -> 1.18 -> 1.19 -> 1.20 -> 1.21.

**Comment by Callisto13** [comment]
Okay I have a totally random theory.. but I think the random sha is because you were using a rc, not a full release (and i was using a locally build binary). Could not repro on full release of 58. Gonna test out.

**Comment by Callisto13** [comment]
handing over to @aclevername while i am away for the next week

**Comment by benjiro** [comment]
Just run into the same issue after upgrading to 1.21 then running the `eksctl utils update-kube-proxy` it seems AWS has decided to change the way they version kube. https://github.com/aws/containers-roadmap/issues/1404#issuecomment-884751824

**Comment by aclevername** [comment]
@benjiro is correct, the format of the version we are getting back from the kubernetes API has changed with `1.21`.

## 1.20 and earleir
[Kubernetes API call to get the version would return](https://github.com/weaveworks/eksctl/blob/635faf0e478e223c9473a3206038358e6ab95af3/pkg/kubernetes/client.go#L122)
```
v1.20.7-eks-8be107
```
this would then get trimmed down to `1.20.7` by our [parser](https://github.com/weaveworks/eksctl/blob/635faf0e478e223c9473a3206038358e6ab95af3/pkg/kubernetes/client.go#L127) 

## 1.21
[Kubernetes API call to get the version would return](https://github.com/weaveworks/eksctl/blob/635faf0e478e223c9473a3206038358e6ab95af3/pkg/kubernetes/client.go#L122)
```
v1.21.2-13+d2965f0db10712
```
this however would not get trimmed down to `1.21.2`, but instead remains as `v1.21.2-13+d2965f0db10712` 

I think we just need to update our parser logic. 

It also appears that since `1.18` all builds are `build.2`, so I think we should also update the code to handle this.

**Comment by aclevername** [comment]
thanks @benjiro for fixing this https://github.com/weaveworks/eksctl/pull/4021

Fix will be out in the next release :smile:

**Comment by BitProcessor** [comment]
@aclevername @Callisto13  I ran into this exact same issue with eksctl 0.71.0 today
Updated EKS cluster to 1.21 ; ran `eksctl utils update-kube-proxy --cluster <cluster> --approve`
Got stuck with a crashing `602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/kube-proxy:v1.21.2-eksbuild.1 `instead of `602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/kube-proxy:v1.21.2-eksbuild.2`

**Comment by aclevername** [comment]
> kube-proxy:v1.21.2-eksbuild.1

@BitProcessor thanks for letting us know. We've got an issue here to improve this process https://github.com/weaveworks/eksctl/issues/4344 - once we implement this it will solve the problem. We'll try to prioritise it asap

**Comment by BitProcessor** [comment]
@aclevername Thanks for the update. Is there a way to cleanly specify an override in the meanwhile?

Currently, I'm using `--skip-outdated-addons-check=true` to skip pass the kube-proxy error eksctl throws after manually overriding the daemonset with the build.2 image. Wondering if there's a better way? 🤔
