### ISSUE TITLE
Environment variables is not be set with overrideBootstrapCommand on non managed nodegroup

### ISSUE THREAD

**Issue by cw-sakamoto** [weaveworks/eksctl#4055]
**What help do you need?**

If I use `overrideBootstrapCommand` on non managed nodegroup, `/etc/eksctl/kubelet.env` and so on are not generated and it seems difficult to set environment variables, is this a specification?

At point https://github.com/weaveworks/eksctl/blob/main/pkg/nodebootstrap/userdata.go#L118-L133, if `overrideBootstrapCommand` is specified, some of the processing is skipped.

I want to change only `bootstrap.al2.sh` with overrideBootstrapCommand to change kubelet container runtime to `containerd`. In this case, I cannot set the necessary environment variables(`MAX_PODS`,`NODE_TAINTS`, etc), making it difficult to start.

eksctl version: 0.59.0
eks: 1.21

**Comment by Callisto13** [comment]
Hi @cw-sakamoto thanks for asking.

The purpose of `overrideBootstrapCommand` is to **completely** cancel any bootstrapping set up by `eksctl` in order to handle the entire thing yourself. This includes any environment variables. We don't have a concept of "partially override the bootstrap".

Having said that, I could see the value in setting up the vars file anyway so that those values are available to the user if they wish to use them. I will bring it up with the team 👍 .

> I want to change only bootstrap.al2.sh with overrideBootstrapCommand

You will not be able to change that script, as it will not have been loaded onto the AMI with userdata. When you use `overrideBootstrapCommand` you have to call [`/etc/eks/bootstrap.sh`](https://github.com/awslabs/amazon-eks-ami/blob/master/files/bootstrap.sh) directly. [Eg](https://github.com/weaveworks/eksctl/blob/main/examples/22-managed-nodes-launch-template.yaml#L32-L34). Basically whatever script you set in `overrideBootstrapCommand` _becomes_ `bootstrap.al2.sh`: this is the intended purpose of the option.

> I cannot set the necessary environment variables

You _should_ be able to set anything you want in your `overrideBootstrapCommand`, eg: 

```bash
  overrideBootstrapCommand: |
    #!/bin/bash
    export FOO=etc
    # edit some files maybe etc
    /etc/eks/bootstrap.sh <cluster-name> --kubelet-extra-args '--node-labels=etc --register-with-taints=etc' $FOO --container-runtime containerd
```

Lastly, we are about to merge https://github.com/weaveworks/eksctl/pull/4051, so in the next release there will be a config option in `eksctl` to set containerd easily.

**Comment by cw-sakamoto** [comment]
@Callisto13 Thanks for your reply.

>Having said that, I could see the value in setting up the vars file anyway so that those values are available to the user if they wish to use them. I will bring it up with the team

Thank you! 😃

I am very excited about this pull request(https://github.com/weaveworks/eksctl/pull/4051).
I commented https://github.com/weaveworks/eksctl/pull/4051#issuecomment-894113563

**Comment by Callisto13** [comment]
Cool 😎 . We release every Friday, so that PR might not make it in today, in which case it will be out in 0.62.0-rc.0
