### ISSUE TITLE
duplicate tags when set via --tags

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#413]
I observed this in the output of our integration tests:

```
2019-01-09T15:54:05Z [▶]  CreateStackInput = {
  Capabilities: ["CAPABILITY_IAM"],
  StackName: "eksctl-hilarious-rainbow-1547049243-cluster",
  Tags: [{
      Key: "eksctl.cluster.k8s.io/v1alpha1/cluster-name",
      Value: "hilarious-rainbow-1547049243"
    },{
      Key: "eksctl.cluster.k8s.io/v1alpha1/description",
      Value: "eksctl integration test"
    },{
      Key: "eksctl.cluster.k8s.io/v1alpha1/description",
      Value: "eksctl integration test"
    }],
  TemplateBody: ....
```

**Comment by mumoshu** [comment]
https://github.com/weaveworks/eksctl/blob/4d872f7a2732f90ec0cbb2b70a0ae52d378f4c1c/pkg/cfn/manager/api.go#L57-L62

This seems problematic because `tags` and `c.sharedTags` contains the exact same set of tags passed via `eksctl create cluster --tags`.

The sourec is `tags`:

https://github.com/weaveworks/eksctl/blob/3b8a4d9441dc16a3d21e1d544a67f43ab6617ffe/pkg/cfn/manager/cluster.go#L21

The source of `c.sharedTags`:

https://github.com/weaveworks/eksctl/blob/4d872f7a2732f90ec0cbb2b70a0ae52d378f4c1c/pkg/cfn/manager/api.go#L42-L49

**Comment by mumoshu** [comment]
Assuming cloudformation deduped the tags, I avoided reimplementing deduping in `eksctl/pkg/cfn/manager/api.go`. Instead, I just fixed the code path seemed to be written in a wrong assumption that StackCollection dedups tags.

Please see #415 for the actual change!
