### ISSUE TITLE
Conflicting docs on private cluster creation

### ISSUE THREAD

**Issue by brsolomon-deloitte** [weaveworks/eksctl#4136]
From https://eksctl.io/usage/vpc-networking/#managing-access-to-the-kubernetes-api-server-endpoints:

> EKS does allow creating a configuration which allows only private access to be enabled, but **eksctl doesn't support it during cluster creation as it prevents eksctl from being able to join the worker nodes to the cluster.**

Then from https://eksctl.io/usage/eks-private-cluster/:

> **eksctl supports creation of fully-private clusters that have no outbound internet access and have only private subnets.** VPC endpoints are used to enable private access to AWS services.

These (bold added) seem to be in direct conflict.

In our limited experience with `eksctl` thus far, it's the first statement that has been true. We get what looks to be a timeout in the join stage when attempting to create a private cluster.

**Comment by brsolomon-deloitte** [comment]
not stale

**Comment by Skarlso** [comment]
Hey @brsolomon-deloitte!

I understand that the docs might be confusing. What's happening here is that, `eksctl` provides a way of creating a fully functioning private cluster regarding the whole of the creation process because, it first set it to public so the control plane cluster api is reachable and the nodes can join and then once everything is done, will set it to fully private. From that point on you can only use eksctl and kubectl while inside the respective VPC that `eksctl` created.

Does this answer you question?
