### ISSUE TITLE
nodegroups delete DeletionFailure

### ISSUE THREAD

**Issue by DevOpserzhao** [weaveworks/eksctl#4203]
Looking at the Cloudformation stack this  nodegroups  not exist

eksctl get nodegroup    --cluster=eksctl-eks-prod01-cluster
2021-09-09 10:00:54 [ℹ]  eksctl version 0.66.0
2021-09-09 10:00:54 [ℹ]  using region ap-east-1
CLUSTER                         NODEGROUP                               STATUS            
eksctl-eks-prod01-cluster       ng-1-workers-b                          DELETE_FAILED   

aws console:
Ec2SecurityGroupDeletionFailure | DependencyViolation - resource has a dependent object

**Comment by nikimanoledaki** [comment]
Hi @DevOpserzhao, sometimes resources (especially Security Groups and networking-related resources) fail to get deleted. This is something we're working on. :)

Deleting the nodegroup again with `--wait --force` might be a solution:
```
eksctl delete nodegroup --cluster eksctl-eks-prod01-cluster --region ap-east-1 --name ng-1-workers-b --wait --force
```

If it doesn't, could you please share your config file and any steps so that we can reproduce it? Thank you!

**Comment by DevOpserzhao** [comment]
> Hi @DevOpserzhao, sometimes resources (especially Security Groups and networking-related resources) fail to get deleted. This is something we're working on. :)
> 
> Deleting the nodegroup again with `--wait --force` might be a solution:
> 
> ```
> eksctl delete nodegroup --cluster eksctl-eks-prod01-cluster --region ap-east-1 --name ng-1-workers-b --wait --force
> ```
> 
> If not, could you please share your config file and any steps so that we can reproduce it? Thank you!
> 
> Edit: If you could also share the full error stack from the AWS console that would also be great

but  the Cloudformation stack for  nodegroups ng-1-workers-b is not exist

**Comment by nikimanoledaki** [comment]
I'm not sure that it's fully been removed since the `DELETE_FAILED` status indicates that it's stuck in a broken state. What do you get if you try to force deleting it with `--wait --force`? This might get rid of the dependant object, otherwise this is a bug and I could try to reproduce it with a bit more info about your configuration such as your config file if you used one (with any sensitive info redacted). Thank you!
