### ISSUE TITLE
containerd runtime integration test failing

### ISSUE THREAD

**Issue by aclevername** [weaveworks/eksctl#4294]
failed 3 times in a row: https://github.com/weaveworks/eksctl/runs/3790538994?check_suite_focus=true

times out when waiting for the nodegroup to report healthy
```
[0] 2021-10-04 16:25:12 [ℹ]  adding identity "arn:aws:iam::<redacted>:role/eksctl-it-crud-floral-rainbow-163-NodeInstanceRole-1NIOK5ODMQKJI" to auth ConfigMap
[0] 2021-10-04 16:25:12 [▶]  saved auth ConfigMap for "test-containerd"
[0] 2021-10-04 16:25:13 [ℹ]  nodegroup "test-containerd" has 0 node(s)
[0] 2021-10-04 16:25:13 [ℹ]  waiting for at least 2 node(s) to become ready in "test-containerd"
...
```

inspecting `kubectl get nodes` shows the nodes as not registered

**Comment by Skarlso** [comment]
:facepalm: this test should be expected to fail. How the freck did it not fail so far????!! :D

**Comment by aclevername** [comment]
@Skarlso didn't you add it :joy: ? https://github.com/weaveworks/eksctl/pull/4051/files

**Comment by Skarlso** [comment]
Okay, now I know what the problem is actually. The test makes no sense. The containerd setting is only ever applied to unmanaged nodegroups anyways, because the setting doesn't exist on the managed nodegroup path.

However, then this should just pass, right? Because the setting is just ignored. Why did it start failing then? No idea... It times out and that's it. I tried testing it locally, works fine. I'm gonna just remove this test, because it doesn't make any sense. The feature is tested through unit tests.

**Comment by Skarlso** [comment]
@aclevername Yeah, I did. :DDDD And now, I'm gonna delete it. :D

**Comment by Skarlso** [comment]
Wait. No. Hang on. What am I saying. This should work. :D

**Comment by Skarlso** [comment]
I got confused because `nodegroups` IS `unmanaged nodegroups`. So this should totally work. But it times out on CI.
