### ISSUE TITLE
As a user of karpenter I want to be able to update the AWS resources associated to it

### ISSUE THREAD

**Issue by aclevername** [weaveworks/eksctl#4432]
Follow up from https://github.com/weaveworks/eksctl/issues/4430

As a user of karpenter
I want to be able to update the AWS resources eksctl created for it
So that I can successfully upgrade the karpenter installation myself manually

## Background
As part of https://github.com/weaveworks/eksctl/issues/4430 we added support for:
- creating the various AWS resources required for karpenter
- installing the helm chart

As new versions of karpenter gets released it will require new AWS resources- e.g. new additions to the policies attached to the IAM role. I should be able to update the AWS resources eksctl created via a command, so that I can update my karpenter installation.

## Proposal
a new command:
```
eksctl utils update-karpenter-resources
```

*Naming open to suggestion*. It needs to convey that *it only updates the AWS resources, not karpenter itself!*. We don't want eksctl becoming a helm-wrapper package manager. This command should have all the default flags:
```
General flags:
  -c, --cluster string       EKS cluster name
  -r, --region string        AWS region
  -f, --config-file string   load configuration from a file (or stdin if set to '-')
      --approve              Apply the changes

AWS client flags:
  -p, --profile string   AWS credentials profile to use (overrides the AWS_PROFILE environment variable)

Common flags:
  -C, --color string   toggle colorized logs (valid options: true, false, fabulous) (default "true")
  -h, --help           help for this command
  -v, --verbose int    set log level, use 0 to silence, 4 for debugging and 5 for debugging with AWS debug logging (default 3)
```

As part of https://github.com/weaveworks/eksctl/issues/4430 we created the AWS resources in its separate stack. The implementation should just be to update the stack via a changset.

## Acceptance Criteria
Happy path :partying_face: 

- As an eksctl user
- Who has a pre-existing eksctl cluster with karpenter installed
- When I run `eksctl utils update-karpenter-resources -f config.yaml`
- I can inspect the cloudformation stack to see that AWS related karpenter resource are updated to the latest requirements
- I should find relevant docs for this

**Comment by Himangini** [comment]
During PR review decide a proper name for this command

**Comment by Skarlso** [comment]
Thinking about this, it might be a bit tricky. Which resources do we want to update? Right now, the Helm Chart and helm installation are not tracked as part of the stack or something like that. So even if you find the stack ( which is tagged ) those are only the IAM resources. The Helm install, of course, can't be tracked.

That said, if we are talking about the actual Karpenter chart, than the following will need to be implemented:

- get the cluster ( `--cluster <name>` )
- implement `helm upgrade` ( this shouldn't be THAT hard, since we already have install and upgrade is almost similar to that. Check out this file: https://github.com/helm/helm/blob/main/cmd/helm/upgrade.go
( We don't care about the dependencies, and don't care about `--install` either. Just construct the client using `actions` like in install, then do a locateChart, and RunWithContext. The rest will be done by the SDK. ).
- call that on the cluster and pray to all the gods

**Comment by aclevername** [comment]
> Thinking about this, it might be a bit tricky. Which resources do we want to update? Right now, the Helm Chart and helm installation are not tracked as part of the stack, or something like that, since it's and installed component on the cluster. So even if you find the stack ( which is tagged ) those are only the IAM resources.
> 
> That said, if we are talking about the actual Karpenter chart, than the following will need to be implemented:
> 
> * get the cluster ( `--cluster <name>` )
> * implement `helm upgrade` ( this shouldn't be THAT hard, since we already have install and upgrade is almost similar to that. Check out this file: https://github.com/helm/helm/blob/main/cmd/helm/upgrade.go
>   ( We don't care about the dependencies, and don't care about `--install` either. Just construct the client using `actions` like in install, then do a locateChart, and RunWithContext. The rest will be done by the SDK. ).
> * call that on the cluster and pray to all the gods

I think we speciffically don't want to be responsible for upgrading the helm chart, eksctl is then becoming a wrapper around helm (doing a helm install as part of create is already pushing the limits of what I think is okay for eksctl). I think the intention was that eksctl could create/update all the karpenter-related AWS resources, since that part is more difficult for the user as the resources are already managed by eksctl.

**Comment by Skarlso** [comment]
So, the service account, the mapping and the iam resources?

**Comment by aclevername** [comment]
> So, the service account, the mapping and the iam resources?

yep

**Comment by Skarlso** [comment]
Ok cool.

**Comment by Skarlso** [comment]
Working on this, I realised an important question. How do we want to update these things if none of the created resources are user facing at all? They aren't in the config file and they, actually, need to be of a very specific name for Karpenter. We don't want the user to mess with them.

If there is a new thing available from Karpenter and we have to update `eksctl` with new things, especially with something like naming, we can't update that in place, right? Since karpenter would have to be reinstalled anyways to get the new names and policies and permissions.

**Comment by Himangini** [comment]
> Working on this, I realised an important question. How do we want to update these things if none of the created resources are user facing at all? They aren't in the config file and they, actually, need to be of a very specific name for Karpenter. We don't want the user to mess with them.
> 
> If there is a new thing available from Karpenter and we have to update `eksctl` with new things, especially with something like naming, we can't update that in place, right? Since karpenter would have to be reinstalled anyways to get the new names and policies and permissions.

@cPu1 do you have any thoughts around this issue?

**Comment by cPu1** [comment]
> Working on this, I realised an important question. How do we want to update these things if none of the created resources are user facing at all? They aren't in the config file and they, actually, need to be of a very specific name for Karpenter. We don't want the user to mess with them.

The AWS resources for Karpenter are created as part of a CloudFormation stack, so IMO, the update command should add/update the resources in the existing stack and submit the changeset. To force Karpenter to use the new resources, we can do a `helm upgrade` (using the Helm library) with the latest Helm chart and values.

What do you mean by user facing?

**Comment by Skarlso** [comment]
We specifically don't want to do anything else with helm because `eksctl` shouldn't be a package manager.

What I'm saying is that the resources that are created are "hidden" from the user. How would you upgrade them? To what from where? Here are my proposals with explanation:

## Upgrade done by the user

So if a user wishes to update the resources created by eksctl, things like the roles and permissions, we would have to surface those into the configuration inside the Karpenter config. Things like the name of the role or the attached policies. This is dangerous because Karpenter requires specific named resources and the user could mess those up. We could say that we don't care of course, but that might not be a nice user experience.

## Upgrade from our side if Karpenter changes things

If Karpenter changes some requirements around what they require and that would prompt an update in the IAM resources because they suddenly require a new policy, that would mean we'd have to release a new version of `eksctl` anyways and the user would have to completely re-install Karpenter because the new version needs to use the new resources. In that case, an upgrade doesn't make sense, since they will reinstall things using Helm. For that, nuking the installation is a better option and then reinstalling all the resources.

This still requires a bit of fiddling but requires a different kind of update. Something like, `eksctl update karpenter`.

BUT! This, actually requires a case by case code. Depending on the update needed, if the user doesn't want to kill the whole cluster and reinstall Karpenter, we could update existing resources and leave upgrading Karpenter to the user. Which means, right now, this ticket is not doing anything. If there is a change in policy requirement, we have to implement that when there is a need for it and add the command at that point updating that specific resource.

## Do not do anything with this ticket right now

My money is on this option actually. If there is an update required for Karpenter there will be new code needed from `eksctl` anyways. The user will have to upgrade Karpenter, and then run eksctl to upgrade the specific resource IF THERE IS A NEED. Chances are the Karpenter will not require any new policies or rename their IAM roles any time soon and I don't think we want the user to do that randomly either.

That's my 2 cents on this issue. WDYT?

**Comment by Himangini** [comment]
@akestner @josefaworks Do you have any preference for the suggestions from @Skarlso in the above comment?

**Comment by josefaworks** [comment]
I'm onboard with "Do not do anything with this ticket right now"
@akestner if this option is ok with you as well, let's set up a meeting to establish a smooth process for getting updates about karpenter :)

**Comment by akestner** [comment]
I agree with @Skarlso for now. We don't have any plans to meaningfully change the AWS resources / permissions required for Karpenter in the near future and will work with the `eksctl` team whenever there are major changes coming down the pipe in Karpenter. Let's sit tight for now.

**Comment by Skarlso** [comment]
Thanks, Alex!

**Comment by Himangini** [comment]
Closing this since we agreed to not do anything right now.
