### ISSUE TITLE
eksctl: Doesn't fail with wrong node type selection

### ISSUE THREAD

**Issue by kethavathsivanaik** [weaveworks/eksctl#4515]
EKS supports the following Node Types: t2, m3, m4, m5, c4, c5, i3, r3, r4, x1, p2 and p3

The eksctl command doesn't fail on wrong Node type selection. It's creating the cluster with those node type and the pods are failing with Crash Loop Back Off Error. Figured out the issue after hours of debugging the Cluster for the issue.

**Comment by Skarlso** [comment]
Hello!

Thank you for your issue! I'm sure we can do something about this to make the user experience better 🤔! It would be awesome if we could query EKS for supported nodes. That way we don't hardcode anything. We'll look into it. :)

**Comment by cPu1** [comment]
eksctl does not validate if an instance type is supported before proceeding with nodegroup creation. Failing early for an unsupported instance type would be a nice UX improvement. We'll add this to the backlog, but in the meantime, you can somewhat work around this by using managed nodegroups, for which the API will fail with an error early instead of waiting for the nodes to join the cluster.

**Comment by Himangini** [comment]
We will add a check to fail early to improve the Ux as suggested by @cPu1 above.

**Comment by Himangini** [comment]
We are dropping this for now since there's an overhead of maintaining the list of supported instance types.
