### ISSUE TITLE
Flux binary existence is not checked prior to running `create cluster` with flux

### ISSUE THREAD

**Issue by pkit** [weaveworks/eksctl#4516]
**What were you trying to accomplish?**
`eksctl create cluster -f cluster.yaml`

**What happened?**

`[!]  exec: "flux": executable file not found in $PATH`

**How to reproduce it?**
See above
It's obvious that flux will fail if it's not in path.

**Versions**

```
$ eksctl info
eksctl version: 0.76.0
kubectl version: v1.21.2-13+d2965f0db10712
OS: linux
```

**Comment by Skarlso** [comment]
Hello. Thank you for your issue!

I'm curious what would you like to happen in this case? Does this fail immediately, or does this happen after a while?

If it fails immediately, then it's okay, since eksctl would say the same thing as the above error anyways. If some resources have already been created and it fails THEN we can fail earlier for sure.

Thanks!

**Comment by pkit** [comment]
Hi, it fails after everything is created, like 30 minutes in.
I think it's kinda part of #3664 but can be tested much easier than what's proposed there.

**Comment by Skarlso** [comment]
Ah yes, that is unfortunate for sure. Thanks for flagging this!
