### ISSUE TITLE
eksctl sometimes fails to clean up cloudformation stack.

### ISSUE THREAD

**Issue by nrh** [weaveworks/eksctl#4538]
**How to reproduce it?**
`$ eksctl create cluster --name foo --region *region-with-maxed-out-vpcs*`
[...]

> VPC: CREATE_FAILED – "The maximum number of VPCs has been reached. (Service: AmazonEC2; Status Code: 400; Error Code: VpcLimitExceeded; Request ID: asdf; Proxy: null)"
> 1 error(s) occurred and cluster hasn't been created properly, you may wish to check CloudFormation console                                                                                                       
> to cleanup resources, run 'eksctl delete cluster --region=foobar --name=foo'

`$ eksctl delete cluster --name foo --region *region-with-maxed-out-vpcs*`
[...]
> Error: unable to describe cluster control plane: ResourceNotFoundException: No cluster found for name: foo.

`$ eksctl create cluster --name foo --region *region-with-maxed-out-vpcs*`
[...]
> creating CloudFormation stack "eksctl-foo-cluster": AlreadyExistsException: Stack [eksctl-foo-cluster] already exists                                                                                        
>        status code: 400, request id: asdf

I'd suggest in this and other cluster-creation failure cases, an existing CFN stack name should be dealt with more gracefully, or 'eksctl cluster delete' should attempt to delete the cfn stack even when the cluster itself does not exist.

**Versions**
```
$ eksctl info
eksctl version: 0.76.0
kubectl version: v1.23.0
OS: darwin
```

**Comment by Skarlso** [comment]
Similar to https://github.com/weaveworks/eksctl/issues/4438

I'll answer something in this one regarding to the other one as well.

Yes, this is a known issue. Sadly, we can't just randomly delete stacks and usually, we do, but sometimes it fails because it's in a ROLLBACK state and can't be deleted just manually, after getting rid of the offending resources.

You could try next time doing something like `eksctl delete cluster -f configfile.yaml --wait`. Wait will make sure that cloudformation stack is also gone. Most of the times that will work, but sometimes it doesn't. Deleting AWS resources isn't always trivial. Sometimes, the ENI and the NAT get stuck because of a VPC dependency. The ENI can't be deleted because the NAT is using it and the NAT couldn't be released. It's a circle dependency which is annoying, but can't really be helped.

Try using `--wait`. If that doesn't help, come back on this ticket, and we'll figure something out. 

Thanks! :)
