### ISSUE TITLE
[Spike] Evaluate updating the cluster's CloudFormation stack for update commands

### ISSUE THREAD

**Issue by cPu1** [weaveworks/eksctl#4543]
`eksctl create cluster` creates a CloudFormation stack for the cluster, but for subsequent cluster update operations, it issues separate AWS API calls instead of updating the CloudFormation stack. Now that there's almost complete feature parity with EKS CloudFormation and the API, evaluate whether eksctl can update the CloudFormation stack directly for update operations.

Timebox: 1-2 days
Outcome: details on this ticket.

**Comment by aclevername** [comment]
WIP

## Background
When eksctl was first created cloudformation support for various EKS resources was limited to creation and deletion only. That mean't that if you wanted to update a managed nodegroup for example you would have to issue an API call to do so. The following commands are example of this:

- `eksctl update nodegroup` updates the EKS managed nodegroups [update config](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-eks-nodegroup-updateconfig.html) https://github.com/weaveworks/eksctl/blob/b3b9d129b4d13bae853765fbd7e28f1c7b5a308d/pkg/actions/nodegroup/update.go#L47-L51
- `eksctl scale nodegroup` updates the EKS Managed nodegroups [scale config](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-eks-nodegroup-scalingconfig.html) https://github.com/weaveworks/eksctl/blob/b3b9d129b4d13bae853765fbd7e28f1c7b5a308d/pkg/actions/nodegroup/scale.go#L104-L107
- `eksctl upgrade cluster` updates thes EKS cluster version https://github.com/weaveworks/eksctl/blob/b3b9d129b4d13bae853765fbd7e28f1c7b5a308d/pkg/eks/update.go#L279-L305
- `eksctl utils update-cluster-endpoints`

**Comment by Skarlso** [comment]
Well done Jake, nice write up. Three things come to mind when reading:

- The CI thing, is annoying, but to be honest, if people are using an outdated version of eksctl, like we did with flux, then the recommendation will always be to update. And hopefully, CI based stacks are throwaways most of the time anyways
- What if we would provide a separate update function so people could ease into using this new way and decide and update form themselves because making it the default option and slowly rotating out the old functionality (isn't there a thing in eksctl to do that already? I remember something written about features being deprecated procedure)
- I'm all for single source of truth. Did we think about people using terraform and what they would have to change for that?
- How about using the version tag to identify what cluster needs to be converged and THEN tag them as converged? We have this tag `alpha.eksctl.io/eksctl-version` if this is lower than `x` then converge either way, then mark the stack as converged?

**Comment by aclevername** [comment]
> * What if we would provide a separate update function so people could ease into using this new way and decide and update form themselves because making it the default option and slowly rotating out the old functionality (isn't there a thing in eksctl to do that already? I remember something written about features being deprecated procedure)

We could introduce an `eksctl apply` that uses this logic, but the problem still remains that any mix-matching of stack vs api driven updates will cause strange UX


> * I'm all for single source of truth. Did we think about people using terraform and what they would have to change for that?

I don't follow :thinking: can you expand?

> * How about using the version tag to identify what cluster needs to be converged and THEN tag them as converged? We have this tag `alpha.eksctl.io/eksctl-version` if this is lower than `x` then converge either way, then mark the stack as converged?

Thats certainly a possibility yes!

**Comment by Skarlso** [comment]
> I don't follow 🤔 can you expand?

I don't know, just had it as an idea. :D :D

**Comment by nikimanoledaki** [comment]
Great stuff!!!

Could you expand a bit on what the behaviour of `eksctl apply` would be and how it would be a solution for this? Would it essentially cover the following two points that you wrote about?
```
a. Scan the cluster to detect its real status for all the relevant fields
b. Update the stack template to match the real world state.
```

I may also be missing some context since the conversations around `eksctl apply` kind of predate me. If there are any links to past discussions around this, those may be helpful to add here to share context. :)

**Comment by aclevername** [comment]
> Could you expand a bit on what the behaviour of `eksctl apply` would be and how it would be a solution for this? Would it essentially cover the following two points that you wrote about?
> 
> ```
> a. Scan the cluster to detect its real status for all the relevant fields
> b. Update the stack template to match the real world state.
> ```
> 
> To what extent would it be like `kubectl apply`?
> 
> I may also be missing some context since the conversations around `eksctl apply` kind of predate me. If there are any links to past discussions around this that you think would be helpful, those may be helpful to add here to share context. :)

The proposal definitely covers it as a whole.

As for how it fits into this, what I meant to say that if we shifted to updating the stack, commands like `eksctl utils update-cluster-endpoints` which currently just updates a unique/isolated piece of configuration, would instead reconcile the whole stack to the cluster template. So its modifying *a lot*. This might be what you want `eksctl apply` to do, same as `kubectl apply`, take this yaml, and make its entire contents the state of the world. The current `eksctl utils update-cluster-endpoints` is much more like a `kubectl patch` (e.g. `kubectl patch node ng-1 -p '{"spec":{"unschedulable":true}}'` to just *only* `unschedulable` to true)

**Comment by Himangini** [comment]
@mikestef9 @josefaworks do you have any thoughts on this proposal?

**Comment by cPu1** [comment]
>Users who revert to using an older eksctl version (e.g. switching workstations between team members, CI using older versions) will see a strange set of behaviours, mixing API driven commands and stack update commands. This will be quite a horrible UX


We shouldn't try to support this case as it will not work if an older version of eksctl is used on a cluster created with `0.80.0`, as goformation will not recognise the additional fields that were added recently.

**Comment by aclevername** [comment]
> We shouldn't try to support this case as it will not work if an older version of eksctl is used on a cluster created with `0.80.0` and above, as goformation will not recognise the additional fields that were added recently.

I believe this will be a problem regardless as https://github.com/weaveworks/eksctl/pull/4526 already introduces those new fields

**Comment by aclevername** [comment]
Closing for now as we agree not to do go down this route due to the implications detailed above
