### ISSUE TITLE
[SPIKE] Investigate and fix force pushing to docs branch

### ISSUE THREAD

**Issue by Skarlso** [weaveworks/eksctl#4575]
Our tag-release action is using a build script which force pushes to the `docs` branch. This should be stopped. Investigate what we can do about it.

```
# Update the site by putting everything from the release into the docs branch
git push --force origin "${release_branch}":docs
```

Timebox: 2 days

**Comment by cPu1** [comment]
This has to do with how the release branches are updated and pushed, because they end up with commits the `main` branch does not have, preventing Git from doing a normal push to the `docs` branch.

**Comment by cPu1** [comment]
> This has to do with how the release branches are updated and pushed, because they end up with commits the `main` branch does not have, preventing Git from doing a normal push to the `docs` branch.

I have worked on a solution that eliminates the need for force-pushing and having a dedicated branch (`docs` in this case) for publishing docs. We use Netlify to publish our docs and it has a feature for triggering deployments by sending an HTTP request specifying the branch we want deployed. The new approach triggers the Netlify deployment as part of the `Release` workflow using GitHub actions, so we'd no longer need to force-push to `docs`, or use it at all for publishing documentation. 

I have pushed the changes to a [branch](https://github.com/weaveworks/eksctl/compare/main...cPu1:publish-docs?expand=1), but haven't opened a PR yet because I'm evaluating another approach that uses one of the Netlify GitHub actions. 

cc: @mnowster
