### ISSUE TITLE
Avoid redundant calls to DescribeStack, GetStackTemplate

### ISSUE THREAD

**Issue by cPu1** [weaveworks/eksctl#4635]
When handling a command that requires loading information about the cluster, eksctl fetches the cluster's CloudFormation stack to obtain references to resources (like VPC) stored in output variables. This pattern is repeated in every part of the codebase that needs to read the cluster stack, resulting in redundant AWS API calls and slowing down execution of the command. 

Instead, this information should be encapsulated in a type, or fetched from the top-level calling code and passed down to code that needs it. 

Related: #4213

**Comment by cPu1** [comment]
This is also true for `GetStackTemplate` which is called multiple times during the execution of a command.

**Comment by Himangini** [comment]
@cPu1 add the example of the command here

**Comment by Skarlso** [comment]
Going to do this in small, incremental PRs, otherwise it will get overwhelming.

**Comment by Skarlso** [comment]
There is another possible reduction here in `compat.go`:

```go
	if clusterDefaultSG != "" {
		stackSupportsManagedNodes, err = c.hasManagedToUnmanagedSG()
		if err != nil {
			return err
		}
	}
```

And on the next couple lines below it says:

```go
	logger.Info("adding missing resources to cluster stack")
	_, err = c.AppendNewClusterStackResource(false, stackSupportsManagedNodes)
	return err
```

Where `AppendNewClusterStackResource` does another getStackTemplate. But refactoring Append would require some other, nasty edits to another function which does not have the template. And I think that's just not worth it.

**Comment by Skarlso** [comment]
I did try putting a stack template on the StackCollection and then added a function which said GetCachedStackTemplate. But that didn't actually reduce anything because most of the time the stack we are looking for is not the one that is the stack of the StackCollection but the nodegroups or roles stack. Or we needed to call it anyways because updated information was needed. So it just wasn't worth adding it.

Same goes for the stack being created up-front. Not the stack we actually work it most of the time. And in other places, I already made some sane modification to those calls.

And thus, I'm considering this one closed for now. Feel free to re-open if someone wants another stab on this. Or maybe when we refactor that giant stack collection interface things can get better.
