### ISSUE TITLE
if eksctl create cluster fails, no way to clean up the stack

### ISSUE THREAD

**Issue by matti** [weaveworks/eksctl#4662]
```
2022-01-19 17:53:27 [ℹ]  building cluster stack "eksctl-kungen-1-cluster"
2022-01-19 17:53:28 [!]  1 error(s) occurred and cluster hasn't been created properly, you may wish to check CloudFormation console
2022-01-19 17:53:28 [ℹ]  to cleanup resources, run 'eksctl delete cluster --region=eu-north-1 --name=kungen-1'
2022-01-19 17:53:28 [✖]  creating CloudFormation stack "eksctl-kungen-1-cluster": AlreadyExistsException: Stack [eksctl-kungen-1-cluster] already exists
	status code: 400, request id: fce610ce-a478-497f-83b0-867ffa210641
```

but then:
```
eksctl delete cluster --region=eu-north-1 --name=kungen-1
Error: unable to describe cluster control plane: ResourceNotFoundException: No cluster found for name: kungen-1.
{
  RespMetadata: {
    StatusCode: 404,
    RequestID: "21b14c5a-daca-4ed8-aaa7-43742a2ca3f7"
  },
  Message_: "No cluster found for name: kungen-1."
}
```

also noticed here: https://github.com/weaveworks/eksctl/issues/1386#issuecomment-1011372461

**Comment by Skarlso** [comment]
Hi. 

In that issue, they are talking about the cluster, but what's happening actually is that the cloudformation stack is there while the cluster isn't. This happens if the cluster creation failed on the first part. In which case there is no cluster so it says, can't delete cluster. But the stack was already created. The cloudformation stack that is. In that case, `eksctl` can't do too much since it's looking for the cluster. Maybe we can do something like, look for the cloudformation stack as well (maybe we do that already, I'm not sure, I have to check). But an immediate action you can take is to delete the cloudformation stack and then you can move on. Deleting the CF stack will remove all resources associated with the stack that it might have created so far such as VPCs, Security Groups, etc.

**Comment by matti** [comment]
yes, I already deleted the stack and moved on - but imo eksctl should have atleast some utility function to delete the stack (and possibly some other resources that were created, because as a user I'm not sure what was created for me by eksctl)

**Comment by jglick** [comment]
AFAICT the only thing `eksctl` can do to fix this is to use a distinct name for the stack. Rather than `eksctl-$clustername-cluster`, append some random number; or check for the existence of the stack with the expected name but `DELETE_COMPLETE` status before trying to create it (or optimistically try to create it with the current name but catch `AlreadyExistsException`) and try appending a unique suffix. A corollary is that `eksctl delete cluster` would need to be a bit more complicated, as it could not necessarily predict the stack name; it would need to query AWS either using some attribute filter or client-side filtering.

**Comment by Skarlso** [comment]
`eksctl` avoided using some configuration file for a while now which is not the config file that you pass in, but it came up a number of times now to perhaps store the cluster name ( from which the stack name could be derived ). That would mean though, that you can't run eksctl in a CI which scraps the storage or anywhere where there is only ephemeral storage available.

I have to wonder how many time do you get into this situation where eksctl cluster create fails so many times that you get overwhelmed with existing cloudformation stacks that you aren't deleting or have to iterate on the same.

Also, I still haven't managed to reproduce the stack name exists error after I removed the stack by hand and proceeded to create a new stack. Once the cloudformation stack was gone, I could create the same cluster with the same name.

@jglick I know you linked to this 90 days something from stackoverflow, but I just haven't been able to reproduce that.

**Comment by Skarlso** [comment]
Okay, so to test, I created a stack with name `test-stack-name-exists`. Deleted said stack. Waited for it to be gone. Then created the same stack again.

The attached stackoverflow problem talks about completely clean history. And not the fact that you can't reuse the same name I believe.

<img width="472" alt="Screenshot 2022-01-22 at 17 19 16" src="https://user-images.githubusercontent.com/182850/150646835-ed66d20e-e641-40f9-b1dc-215ce4ac245d.png">

**Comment by Skarlso** [comment]
@matti It's a reasonable request I believe to add something like create stacks though. Something like, `eksctl util clean-up`. If you pass a cluster config file to that it could try and determine the stack name it would create and delete that. 🤔 I think that's something that should be relatively easy to add.

The only possible problem would be an unintentional delete of some reason it shouldn't have deleted. Like if a cluster exists with the same name. But we can do something like, you would need to add in `--approve` to do that. I think that's not an unreasonable request. Like you put it nicely, as a user you have no idea what a stack is and why it was added. :)

**Comment by matti** [comment]
my own wrapper on top of eksctl now does: `aws --region $REGION cloudformation delete-stack --stack-name eksctl-$CLUSTER_NAME-cluster` as a workaround

**Comment by jglick** [comment]
> how many time do you get into this situation where eksctl cluster create fails so many times that you get overwhelmed with existing cloudformation stacks that you aren't deleting

Frequently, alas. AZ problems (https://github.com/weaveworks/eksctl/issues/3816#issuecomment-1009340409), session credentials expiring halfway through, and other errors.

I realized that I am using a relatively old version of `eksctl` (0.67.0); perhaps CloudFormation usage changed since then. Will recheck behavior the next time I need to create a cluster.

**Comment by matti** [comment]
I'm also constantly running this as I start clusters in parallel and run out of random quotas (EIP, gateways, and so on)

**Comment by aclevername** [comment]
I think perhaps its worth having the `--force` flag during `eksctl delete cluster` gracefully handle the scenario where the cluster doesn't exist, but the stack does. This should then provide a easy way to clean up. Thoughts?

**Comment by Skarlso** [comment]
@aclevername Sounds good to me. Would force removing the stack if it exists.

**Comment by Skarlso** [comment]
Uh, we already have a force flag `fs.BoolVar(&force, "force", false, "Force deletion to continue when errors occur")`.

@aclevername Shall we extend this flag to continue with removing the stack? Ooor... have an explicit flag, something like `--all` or `--remove-stack` which is explicit?

**Comment by aclevername** [comment]
> Uh, we already have a force flag `fs.BoolVar(&force, "force", false, "Force deletion to continue when errors occur")`.
> 
> @aclevername Shall we extend this flag to continue with removing the stack? Ooor... have an explicit flag, something like `--all` or `--remove-stack` which is explicit?

I meant expanding upon the existing flag, which I think is reasonable

**Comment by Skarlso** [comment]
Makes sense

**Comment by cPu1** [comment]
> I think perhaps its worth having the `--force` flag during `eksctl delete cluster` gracefully handle the scenario where the cluster doesn't exist, but the stack does. This should then provide a easy way to clean up. Thoughts?

Sounds reasonable to me :+1:.

**Comment by Skarlso** [comment]
Okay, so this is actually suspicious. We already have code which should clear any remaining stacks if `--force` is used. :) I'll try to test this now.

**Comment by Skarlso** [comment]
I foounnnd the probleeem! :D Turns out we were doing a cluster check at different point as well before even getting to checking the stack status and initalizing the cluster manager.

We already have code for removing a stuck cluster stack, but turns out, it was never called. This is a bug! :))) I'll have a fix soon :)

**Comment by a0149659** [comment]
I got this reply from AWS Support, I hope it helps while the fix is in:

```
Hello Ivan,

This is Varun again from AWS Premium support. At first thank you for being patient while we have worked on your case. 

I have an update for you from the case. Service team has completed the investigation on your case and found the root cause of the issue to be automatic tagging of the cluster resource by eksctl with tag "Name"= "${AWS::StackName}/ControlPlane" on cluster creation. This tagging has been supported by eksctl via CFN since 0.80.0 release [1]. That being said, during investigation we have analyzed the templates from the CFN stack created and noticed that you are using a Key set to "Name" with a value assigned to it and this is resulting in a duplicate tag key and is resulting in the below duplicate key error

================================
Error:

AWS::EKS::Cluster/ControlPlane: CREATE_FAILED – "Resource handler returned message: \"Duplicate key eksctl-eks-sandbox-cluster/ControlPlane\" (RequestToken: 69dade5d-5345-df90-c6e6-41eec36bf5cd, HandlerErrorCode: InternalFailure)
================================

Therefore, the suggested work around to resolve this issue it to avoid adding a tag with key set to "Name" as eksctl is already creating same key with a different value as mentioned above.

I hope the above information is helpful. Please let me know if you have any questions and I will be more than happy to assist.

Have a great day!

[1] https://github.com/weaveworks/eksctl/releases/tag/v0.80.0 

We value your feedback. Please share your experience by rating this correspondence using the AWS Support Center link at the end of this correspondence. Each correspondence can also be rated by selecting the stars in top right corner of each correspondence within the AWS Support Center.

Best regards,
Varun K.
Amazon Web Services
```
