### ISSUE TITLE
DNS failure when privateNetworking==true 

### ISSUE THREAD

**Issue by M00nF1sh** [weaveworks/eksctl#480]
**What happened?**
A description of actual behavior (with error messages).
when creating a cluster using the newest 0.1.19 with privateNetworking==true , The node securityGroup settings don't allow node-to-node communication.
Which blocked communication to kubedns/coredns(which also runnings on worker nodes), and causes DNS requests from these pods fail.

**What you expected to happen?**
When privateNetworking==true, either enable FeatureSharedSecurityGroup, or allow at least UDP(53) ingress traffic from node securityGroup.

**How to reproduce it?**
create an new eks cluster with privateNetworking==true

**Anything else we need to know?**

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
`[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.1.19"}`
$ uname -a
`Darwin 8c8590418854.ant.amazon.com 17.7.0 Darwin Kernel Version 17.7.0: Fri Nov  2 20:43:16 PDT 2018; root:xnu-4570.71.17~1/RELEASE_X86_64 x86_64`
```
Also include your version of `heptio-authenticator-aws`

**Logs**
Include the output of the command line when running eksctl. If possible, eksctl should be run with debug logs. For example:
`eksctl get clusters -v 4`
Make sure you redact any sensitive information before posting.
If the output is long, please consider a Gist.

**Comment by errordeveloper** [comment]
@M00nF1sh thanks! This is something we've already fixed in master, there was issue with defaulting of the `sharedSecurityGroup` field. You can use 0.1.19 and set `sharedSecurityGroup: true` at the nodegroup level, or build from master and bump config version to `v1alpha4` (you might need to make other changes; we don't have all the docs yet, so if you share the config here, I would be happy to review it).

**Comment by M00nF1sh** [comment]
😄 
Thanks for the help.

**Comment by errordeveloper** [comment]
Always a pleasure!
