### ISSUE TITLE
releases are tagged sometimes with v prefix and sometimes without

### ISSUE THREAD

**Issue by matti** [weaveworks/eksctl#4858]
for example `v0.85.0` vs `0.86.0`

This kind of releasing breaks tools like `asdf` - this old issue: https://github.com/weaveworks/eksctl/issues/4199 is now broken again

Summary
- Have a look at [Chetan's pr](https://github.com/weaveworks/eksctl/pull/4765) 
- we ensure that every official github release uses the v prefixed tag.

**Comment by Himangini** [comment]
@matti Thanks for opening the issue. Can you add more details on how the `asdf` is broken again? As far as I can see from the related issue that they are ignoring `v` from the release tag if exists https://github.com/elementalvoid/asdf-eksctl/pull/1.

**Comment by Himangini** [comment]
After going through the releases page I can see `v0.83` was tagged with a `v` after that all the releases are without `v` 
I am guessing this might be the result of migrating the jobs. Either way, we should have a consistent way of tagging releases.

**Comment by matti** [comment]
I just noticed that suddenly my:
```
asdf plugin add eksctl
asdf install ...
``
was broken and this was the reason. I patched my own version of asdf plugin that tries to download first without `v` prefix and then with `v` prefix - so I'm personally good now, others are not.

**Comment by Skarlso** [comment]
> so I'm personally good now.

Great, we can close this ticket then.

> others are not.

If they exist, I'm sure they'll open their own tickets and then we can deal with those issues. :)

Cheers.

**Comment by matti** [comment]
:D

**Comment by Skarlso** [comment]
@pre we agree. Hence Gini's comment: 
>Either way, we should have a consistent way of tagging releases.

We recently switched from circleci to pure Github actions. I'm guessing something went awry during the process.

**Comment by aclevername** [comment]
Just to summarise whats happened:

- Since `0.37.0` we started tagging every release with a and without the `v` prefix. Example:
https://github.com/weaveworks/eksctl/tree/0.80.0
https://github.com/weaveworks/eksctl/tree/v0.80.0
- We pick 1 of those to be the official github release, in the case of the above example it was the one with the `v` prefix

> Related issues:
> 
> * [New Versioning with v prefix causes problems with installing the latest version #4199](https://github.com/weaveworks/eksctl/issues/4199)
> * [inconsistent tags #4328](https://github.com/weaveworks/eksctl/issues/4328)
> * [releases are tagged sometimes with v prefix and sometimes without #4858](https://github.com/weaveworks/eksctl/issues/4858)

As @pre points out we have broken which one is the official github release a few times. It appears we have done that again now. As @matti points out `0.85.0` uses the version without the `v` prefix, breaking the previous behaviour.

As @Skarlso @Himangini said this is was accidental due to a change in the way we cut releases.

## Proposal
I suggest moving forward we ensure that *every official github release uses the `v` prefixed tag*. This is to keep it consistent with what we have done most recently, as well as with what other libraries, e.g. https://github.com/kubernetes/kubernetes/releases/ 

Since `0.85.0` is already out I don't think its worth deleting it and redoing the release process. Rather we should ensure that the following release `0.86.0` (which already has the pre-release out without the `v` prefix https://github.com/weaveworks/eksctl/releases/tag/0.86.0-rc.0) follow this pattern of having the `v` prefix'd tag be the release.

Does this sound good @pre @matti ? We can commit to this going forward and will strive to not accidentally break any further releases

**Comment by matti** [comment]
that https://github.com/elementalvoid/asdf-eksctl/pull/6 already adapts to both.

my two cents: use v or dont, just make it consistent.

**Comment by Skarlso** [comment]
> my two cents: use v or dont, just make it consistent.

Yes. :) Just like Gini said. :)
> Either way, we should have a consistent way of tagging releases.
