### ISSUE TITLE
Behavior of `--managed` is unintuitive (and docs are wrong)

### ISSUE THREAD

**Issue by cartermckinnon** [weaveworks/eksctl#4892]
**What were you trying to accomplish?**
https://docs.aws.amazon.com/eks/latest/userguide/launch-workers.html
```
eksctl create nodegroup \
  --cluster my-cluster \
  --name al-nodes \
  --node-type t3.medium \
  --nodes 3 \
  --nodes-min 1 \
  --nodes-max 4 \
  --ssh-access \
  --managed false \
  --ssh-public-key my-key
```

**What happened?**
This command doesn't work as documented, the value of `--managed` must be passed like `--managed=false`. I believe this is the behavior of any `BoolVarP` flag with a default value of `true`. Using a default value of `false` would result in more ergonomic usage: if the flag is present, the value would be `true`, so the user would not ever need to specify `true` or `false`, they would just omit or include the flag.

**How to reproduce it?**
Run the command on 0.86.0 (same thing on 0.85.0).

**Logs**
```
Error: couldn't create node group filter from command line options: --name=al-nodes and argument false cannot be used at the same time
```

**Anything else we need to know?**
macOS 12.2.1

**Versions**
```
> eksctl info
eksctl version: 0.86.0
kubectl version: v1.22.2
OS: darwin
```

**Comment by Skarlso** [comment]
Interesting. Thanks for pointing this out. That document is on the AWS side, but we'll flag it on our next meeting together. :)

**Comment by cPu1** [comment]
As you noted, the usage `--managed false` is not allowed due to how boolean arguments are handled in [spf13/cobra](https://github.com/spf13/cobra).

>Using a default value of false would result in more ergonomic usage: if the flag is present, the value would be true, so the user would not ever need to specify true or false, they would just omit or include the flag.

When the `--managed` flag was added, its default value was false. But this behaviour was later changed when we made [managed nodegroups the default](https://eksctl.io/usage/managed-nodegroups-announcement/). We'll ask AWS to update the documentation. Thanks for flagging this.

BTW, all of the options used in your command are supported by managed nodegroups, so you can omit the `--managed=false` option and the nodegroup creation will still succeed.

**Comment by fizzbuzzard** [comment]
I’m on the managed nodes team, so I’ll get the docs updated. 😉

**Comment by cartermckinnon** [comment]
I'm on the managed nodes team, so I'll get the docs updated! Thanks. 😊

**Comment by cPu1** [comment]
The docs have been updated: https://docs.aws.amazon.com/eks/latest/userguide/launch-workers.html
