### ISSUE TITLE
Empty get addons as Json output should be empty array

### ISSUE THREAD

**Issue by gdlx** [weaveworks/eksctl#4910]
I'm using `eksctl get addons -o json | jq ...`  in a script to know what addons are already installed and which ones I need to install.

But when no addon is installed, I just get this:
```
2022-03-07 16:07:33 [ℹ]  Kubernetes version "1.21" in use by cluster "my-cluster"
2022-03-07 16:07:33 [ℹ]  getting all addons
2022-03-07 16:07:33 [ℹ]  no addons found
```

No actual Json string is generated meaning Jq will have nothing to parse and I need to add cumbersome logic to handle this case.

Shouldn't ` eksctl get addons -o json` (and maybe other eksctl commands) have a consistent format, and return an empty Json array instead of an empty string when a Json output is requested ?
```
eksctl version: 0.84.0
kubectl version: v1.21.8
OS: linux
```

**Comment by nikimanoledaki** [comment]
Thanks for opening this issue @gdlx. I can confirm this and agree that it would be better UX and more consistent with other eksctl commands. 

As an example, eksctl does return an empty array when specifying `-o yaml` with the following command:
```
eksctl get iamserviceaccount --cluster <cluster-name> -o yaml
2022-03-07 16:39:07 [ℹ]  eksctl version 0.86.0
2022-03-07 16:39:07 [ℹ]  using region us-west-2
[]
```

We do welcome community PRs if you are interested :) Otherwise, someone from the team will pick this up.

**Comment by gdlx** [comment]
I'm not a go developer but as it seems to be a minor change, I'll take a look.
