### ISSUE TITLE
Can't create/get iamserviceaccount

### ISSUE THREAD

**Issue by carlosleoliveira** [weaveworks/eksctl#4918]
**What help do you need?**

I was making some tests in one of my clusters and I don't know what command I have done that now I can't list my iamserviceaccounts or even get a list. I'm seeing two errors:

eksctl get:
metadata of serviceaccounts that exist in Kubernetes will be updated, as --override-existing-serviceaccounts was set
no tasks

eksctl create:
Error: getting iamserviceaccounts: no output "Role1" in stack

I don't have any clue to fix what I've done and already tryed to search and find anything. Thanks.

**Comment by Skarlso** [comment]
Oh-o... I remember doing something around that part. Will take a quick look at this.

**Comment by nikimanoledaki** [comment]
Chiming in to say that there is also more info on how to use `eksctl create iamserviceaccounts` in our docs here, which might be helpful for your specific case: https://eksctl.io/usage/iamserviceaccounts/

**Comment by Skarlso** [comment]
@carlosleoliveira hi!

That is interesting. It looks like it wasn't me. :) But also, it looks like your stack name is somehow defined but it is empty. Like, set to empty string. That's why it can't find it. So I suggest to look for clues around that part. What was the exact command you used to fetch things? I also recommend looking at what Niki pasted in. :) Good luck!

**Comment by carlosleoliveira** [comment]
Hi!
There's a way to revert my stack? I'm send a screenshot of eksctl get iamserviceaccount on my cluster. All other eksctl commands is working. I think that I delete this iamserviceaccount in a wrong way, now I can't find a way to fix.
![image](https://user-images.githubusercontent.com/60003832/160030437-4c4946ae-fae5-468a-8f14-80c2fca505df.png)

**Comment by Skarlso** [comment]
Can you try running `eksctl delete iamserviceaccounts`?

**Comment by ArjunMG** [comment]
Hi @carlosleoliveira ,

I faced the same issue while trying to deploy ALB controller in EKS.
In AWS EKS when you run `eksctl create iamserviceaccount .....` a cloudformation stack will be created in background. 
Go and checkout the Clodformation stack in AWS and see if there is any error creating the stack. 

In my case there was an error in the stack creation because the command was wrong and the stack was marked as failed. I deleted the stack,resolved the error in my command, run the command again and stack created successfully.

![image](https://user-images.githubusercontent.com/37959979/174247068-5d308848-ec89-4526-8962-8d01aed045b6.png)


Please try.

**Comment by dmuiX** [comment]
any solution for this problem?
Can I reset my eksctl config somehow?
My cloud formation stack got rolled back

**Comment by sagaraniltaneja** [comment]
> **What help do you need?**
> 
> I was making some tests in one of my clusters and I don't know what command I have done that now I can't list my iamserviceaccounts or even get a list. I'm seeing two errors:
> 
> eksctl get: metadata of serviceaccounts that exist in Kubernetes will be updated, as --override-existing-serviceaccounts was set no tasks
> 
> eksctl create: Error: getting iamserviceaccounts: no output "Role1" in stack
> 
> I don't have any clue to fix what I've done and already tryed to search and find anything. Thanks.

Kindly check there are high chances roles associated with service acoounts with same name in other regions which are stored on S3 bucket s3 buckets have global affinity to naming convention. Hope this helps
