### ISSUE TITLE
eksctl create iamidentitymapping shouldn't recreate existing roles

### ISSUE THREAD

**Issue by dbgoytia** [weaveworks/eksctl#4957]
### What feature/behavior/change do you want?
When executing the eksctl create iamidentitymapping command, it would be great if the tool didn't create mappings that already exist. This is not great because on CI/CD,  we could lead to continuously adding those roles in the aws-auth files. This means that we would have multiple replicas of the same role, which doesn't make sense.

### Why do you want this feature?
It would be very useful for implementing on CI/CD systems, as day 2 operations of EKS clusters do require maintenance of also the identity mappings.

**Comment by dbgoytia** [comment]
I think the issue with iamidentitymappings is that they are not backed by any CloudFormation stack. I'm wondering if that would make this implementation a bit difficult.

**Comment by tanvp112** [comment]
When there's a duplication, a message will be printed: `...found existing mappings with same arn "arn:aws:iam::xxxxx" (which will be shadowed by your new mapping)`. Similarly, when delete a duplicated entry: `...there are 1 mappings left with same arn "arn:aws:iam::xxxxx" (use --all to delete them at once)`

Because a role can be mapped to different users and the same user may have different roles, it is better that you check first before adding an entry. Example if the following command return a result then you shouldn't call create again: `eksctl get iamidentitymapping -r ... --cluster ...-v 0 | grep <name>`

**Comment by Skarlso** [comment]
In addition to the previous comment:

>I think the issue with iamidentitymappings is that they are not backed by any CloudFormation stack.

But they are. :)

**Comment by mkarise** [comment]
Can we reopen this issue?  @dbgoytia  This is still an issue. The create command adds duplicate entries for the same mapping in the configmap
