### ISSUE TITLE
[Feature] Upgrade Karpenter to 0.8.0

### ISSUE THREAD

**Issue by StarpTech** [weaveworks/eksctl#5023]
### What feature/behavior/change do you want?

Currently, we only allow Karpenter 0.6.x. It should be possible to install the second last minor.

### Why do you want this feature?

Karpenter has fixed [a bunch](https://github.com/aws/karpenter/compare/v0.6.5...v0.8.0) of things.

**Comment by Skarlso** [comment]
@StarpTech Hi. :)

Because Karpenter is still very much in flux, we pin to minor versions in attempt to keep the integration working.

Every minor change can be a breaking change, because Karpenter is in development at the moment. While the Karpenter team tries not to break things, they sometimes can, and should break things when moving about settings or deciding to scrape some thing or do some other thing differently.

Therefor, any minor update to Karpenter will require testing, and code changes. Keep in mind that we accept contributions of all kind if you would like to take a stab at this. :) We will, if time and energy and resources permit, update the Karpenter integration, but right now, that wasn't a priority. 

Cheers!

**Comment by StarpTech** [comment]
I totally agree with you. Does ekctl also take care of migrations? I opened a [ticket](https://github.com/aws/karpenter/issues/1596) in the karpenter repository. IMO it would make sense if the feature is maintained by the team. Out of curiosity, for OSS contributions, is there a discount to work with eksctl?

**Comment by Skarlso** [comment]
> is there a discount to work with aws eks?

I'm afraid not. :D Would be cool though. :D

> I opened a https://github.com/aws/karpenter/issues/1596 in the karpenter repository. IMO it would make sense if the feature is maintained by the team.

The `eksctl` team is the one keeping the versions up-to-date IMHO. But I'm not sure about the procedure. This is relatively recent thing, so we are still working on figuring it out. :)

**Comment by StarpTech** [comment]
Thanks!

**Comment by Himangini** [comment]
There's a 0.9.0 version available so we'll upgrade to this version.
