### ISSUE TITLE
[Bug] `event = watch.Event{Type:"", Object:runtime.Object(nil)}` when waiting for nodegroup

### ISSUE THREAD

**Issue by Skarlso** [weaveworks/eksctl#5108]
From time to time, it appears that the waiter loses the node context:

https://github.com/weaveworks/eksctl-ci/runs/5982018686?check_suite_focus=true

It might be that the node disappears or the waiting times out because of an AWS issue. In that case, we shouldn't keep logging the empty event but fail immediately. Otherwise, we'll fill up the log to 1.800.000+ lines!

The bug is that we don't check if the Watcher closed the channel or not due to an internal error. So we read on a closed channel which returns the default empty value of the event immediately. This is why we get so many log messages. :)

**Comment by Skarlso** [comment]
It looks like we were waiting for two nodes. One of them managed to get ready, but the other was `not ready` for a long time. And then suddenly, the event context just got nil.

**Comment by nikimanoledaki** [comment]
Reopening this to look at the options mentioned in the last comment as possible improvements.

**Comment by Skarlso** [comment]
Note, that I realised that out of these two:

```
- stop logging in case the object is nil -> this will prevent the 1.800.000 million lines of log messages... :D
- another "bug" is that we don't check if the channel is closed so if the Watcher closed the channel, we receive the empty value immediately. That's why we see so many log messages.
```

the first one was actually caused by the second one. So fixing the second one checking the channel, fixed the first one from stopping to occur. :)

**Comment by Skarlso** [comment]
> Nice! :) Thanks for sharing context. So we could just focus on the first one?
> 
> > instead of the weird, self-made for loop with timeout, we can pass in a proper context and timeout after the context is done / cancelled
> 
> Replacing that `for` loop sgtm. :D

Yeah, sounds good. :)

**Comment by cPu1** [comment]
>instead of the weird, self-made for loop with timeout, we can pass in a proper context and timeout after the context is done / cancelled

The manual timeout-based cancellation was replaced with a deadline-based context as part of the deadline-based Context PR. As for passing a deadline-based Context directly to `Watch`, a loop would still be required because it needs to repeatedly read events from the `ResultChan` until the nodes are ready,  it'll only eliminate the `select` statement. But we'll lose the ability to discern between timeout errors and errors from the underlying event stream because I don't see a clean way of checking `context.DeadlineExceeded` errors from the `ResultChan`. 

So I'd suggest keeping the existing context code unchanged, but we can improve debugging failures by logging the full event object when the event type is `watch.Error`.
