### ISSUE TITLE
[Feature] Determine if instance type is available in zone

### ISSUE THREAD

**Issue by rothgar** [weaveworks/eksctl#5128]
### What feature/behavior/change do you want?

It would be nice if eksctl checked if the desired nodegroup instance type was available in a region/zone before selecting the zone or error early if the instance type is not available.

If I create a cluster and ask for a specific instance type (eg t2.small) eksctl will randomly select 3 zones to create the cluster. But if that instance type is not in one of the zones node group will fail to create.

It seems like during zone selection we could loop through the requested instance types (assuming specific types were requested) and use the [DescribeInstanceTypeOfferings](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/ec2#Client.DescribeInstanceTypeOfferings=) to look up if the instance types are offered. If not we should warn or error before creating a cluster we know will fail.

### Why do you want this feature?

To save time when creating clusters with un-supported configuration and reduce errors and time spent troubleshooting.

**Comment by nikimanoledaki** [comment]
Hi @rothgar, thanks for the detailed feature request. :) 

It seems reasonable, while selecting the 3 random AZs and a specific instance type has been selected, that we would validate that each AZ can support the requested instance type using [DescribeInstanceTypeOfferings](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeInstanceTypeOfferings.html). This could however lead to a significant amount of API calls. 

We will discuss this within the team and follow-up here. :)

**Comment by caboteria** [comment]
Thank you for responding to my whinging on Reddit with a well-crafted feature request!

**Comment by Himangini** [comment]
@cPu1 will add the findings here for an implementation plan.

**Comment by Skarlso** [comment]
So the early finding from Niki surmised an interesting problem. Say, you would have three instance types in various node groups ( which is saying less than people would actually use; I've seen configuration files with a lot more, say 10-15 types for GPU, Memory efficient, CPU efficient... etc ) and considering the usage of more AZs, 4 for example, this would quickly escalate into 12 API calls in total. We would be throttled, and we didn't even begin creating things.

This is because the API linked doesn't provide a list of options which it could check internally, but only offers one-by-one checks. I tried searching for anything that could offer a more suitable call which would reduce this problem to at least a couple calls only in case of high combinations, but there are none.

**Comment by Skarlso** [comment]
# Proposition

Call [DescribeInstanceTypeOfferings](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeInstanceTypeOfferings.html) with the following input:

```go
type DescribeInstanceTypeOfferingsInput struct {
    Filters: []*Filter{
        {
            LocationName: "us-west-2",
        },
    }

    // The location type.
    LocationType: "availability-zone",
}
```

Save all availability zone -> instance type relationships in a map and then use the map to look up instance types for availability zones easily without expending more API calls. Limit the number to a 100 which should get you most of the things in the list.

## Possible optimisation

In case there is only a single instance defined, put that instance into the filter so it returns only availability zones that that instance is available in and we don't have to paginate.

**Comment by Skarlso** [comment]
Actually, you can define multiple values for instances which returns on which AZ they are available in 🤦

**Comment by cPu1** [comment]
The proposal should also account for the case where eksctl randomly chooses a set of availability zones (when `availabilityZones` is not set) but one or more instance types in the nodegroups are not supported in some of these AZs. We need to decide if eksctl should attempt to choose AZs that support all the specified instance types rather than failing later when the randomly chosen AZs lack support for the specified instance types.

**Comment by rothgar** [comment]
We may also need to take into account AZs that are local zones. I consistently have problems where one of my regions has a local zone attached and eksctl selects it but cluster creation fails every time.

**Comment by cPu1** [comment]
> I consistently have problems where one of my regions has a local zone attached and eksctl selects it but cluster creation fails every time.

We recently cut a release with a fix that avoids selecting AWS Local Zones if they're enabled in the account (because they were incorrectly being passed to the EKS control plane).

> We may also need to take into account AZs that are local zones.

We also [added support for Local Zones](https://github.com/weaveworks/eksctl/pull/5187) lately but we require explicitly specifying `ClusterConfig.localZones` ([example ClusterConfig file](https://github.com/cPu1/eksctl/blob/main/examples/33-local-zones.yaml)) to enable the feature. More details on the implementation is documented [in this comment](https://github.com/weaveworks/eksctl/issues/4734#issuecomment-1103809860). We can extend this feature request to validate support for the specified instance types in the  `localZones` specified in the nodegroup.
