### ISSUE TITLE
[Bug] It isn't clear how to upgrade nodes and what fields need to be defined or what is supported

### ISSUE THREAD

**Issue by Skarlso** [weaveworks/eksctl#5147]
The documentation for updating nodes or upgrading them isn't clear.

https://eksctl.io/usage/eks-managed-nodes/#updating-managed-nodegroups

The above doesn't say that if you don't define `updateConfig` when you create the nodes, you won't be able to update them. 

The error message that comes when you don't define this field could also be improved:

```
	if ng.UpdateConfig == nil {
		return fmt.Errorf("the submitted config does not contain any changes for nodegroup %s", ng.Name)
	}
```

That message has nothing to do with the fact that we throw it when there is no updateConfig field defined. The config does contain changes, it just doesn't contain an updateConfig. :)

**Comment by nikimanoledaki** [comment]
This is an important issue since we are dropping flag support and supporting new features through the use of config files. 

With flags, you can find out the supported fields by using `--help`. 

How can a user find out which config file fields can be used with a specific command? 

Currently, this has to be added manually to the docs. We don't have a schema or a consistent, automated way of doing this. We also have the [examples](https://github.com/weaveworks/eksctl/tree/main/examples). I wonder if there's a better way of doing this, preferably through the CLI for better UX (like with `--help`). :)
