### ISSUE TITLE
[Feature] managedNodeGroups:  overrideBootstrapCommand get cluster name from variable or metadata.name

### ISSUE THREAD

**Issue by bitva77** [weaveworks/eksctl#5216]
Yeah, in this section here:

```
    overrideBootstrapCommand: |
      #!/bin/bash
      /etc/eks/bootstrap.sh my-cluster-name
```

Is it not possible to just grab the cluster name from `.metadata.name`?  Like, would it ever be anything but the cluster itself?  :)

When dealing with multiple nodegroups it would be nice to just specify like $CLUSTER_NAME or something like that instead and eksctl fills it in from `.metadata.name` automagically.

**Comment by Skarlso** [comment]
Hi!

Thanks for the suggestion. :) It's not configured because this is the bootstrap part from the userdata section of the cloudformation template where it has no knowledge of anything yet. Also, we don't mess with the bootstrapping anymore, so we don't do any customization on that part.

This field is basically passed to the userdata as is. I'm reluctant to do any parsing of it for fear of replacing any value it might have such as $CLUSTER_NAME.

This script is run by eks here https://github.com/awslabs/amazon-eks-ami/blob/master/files/bootstrap.sh This is what you are calling here.

Does this make sense? :)

**Comment by bitva77** [comment]
Ah, gotcha.  That makes sense as to why - sorry, my ignorance on the userdata part.  I get that  :)

I'll close this!  appreciate the fast response.

**Comment by Skarlso** [comment]
No worries! All requests and questions are welcomed! You could write a curl call in the script, but why would you use an api for which you already know the result. 😁
