### ISSUE TITLE
AWS-specific add-ons

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#53]
In no particular order we should consider the following:

- https://github.com/kubernetes-incubator/external-dns
- https://github.com/zalando-incubator/kube-ingress-aws-controller
- https://github.com/kubernetes-sigs/aws-alb-ingress-controller

Some of these add-ons require instance roles and pre-extisting resource (e.g. Route 53 zone for external DNS) etc, so we could ensure that's set up correctly and make things easy for users.

**Comment by StevenACoffman** [comment]
Should also consider:
* https://github.com/uswitch/kiam

(oh gosh, please not kube2iam)

**Comment by errordeveloper** [comment]
I thought EKS provided full IAM integration, is that not the case right now?

**Comment by StevenACoffman** [comment]
The heptio authenticator allows IAM roles to be translated into kubernetes tokens/accounts, but not the other way around. If an app on a pod uses the aws sdk, it will call the ec2 metadata service and be granted the same iam role and permissions as the node.
Custom IAM roles require either injecting credentials via secrets, or intercepting the ec2 metadata service.  kiam (or the more problematic kube2iam) are the current solutions until the community develops something better with SPIFFE and SPIRE perhaps.

**Comment by kgoralski** [comment]
anything that could help labeling nodes as master/node etc?

**Comment by artemyarulin** [comment]
`aws-alb-ingress-controller` would be so nice to have - `eksctl` provides very nice experience for creating the cluster, but once you want to make anything public with ingress then it's all manual

**Comment by leakingtapan** [comment]
Same thing for CSI drivers:
* EBS CSI Driver: https://github.com/kubernetes-sigs/aws-ebs-csi-driver 
* EFS CSI Driver: https://github.com/aws/aws-efs-csi-driver
* FSx CSI Driver: https://github.com/aws/aws-fsx-csi-driver

It would great if user can optionally pick which driver they want and get it auto deployed along with cluster creation

**Comment by leakingtapan** [comment]
What's the status of this issue? Since CSI migration will be alpha in 1.14. The urge to install CSI driver will become more desired in 1.15

**Comment by whereisaaron** [comment]
Probably no rush then @leakingtapan, at the current release rate it will be ~12 months before EKS catches up to 1.15 😄

**Comment by StevenACoffman** [comment]
@jacobtomlinson We encountered a lot of problems that were difficult to diagnose with kube2iam. The future of the kube2iam project seems to be [uncertain](https://github.com/jtblin/kube2iam/issues/132) and there are other issues logged around race conditions, etc. After some research, Kiam seems to be a valid alternative. The developers have [written a post](https://medium.com/@pingles/kiam-iterating-for-security-and-reliability-5e793ab93ec3) on their experience of Kube2iam and why they decided to write Kiam which goes into a lot of detail.

**Comment by jacobtomlinson** [comment]
Thanks for the detailed answer. Those references were exactly what I was looking for.

**Comment by whereisaaron** [comment]
I've evaluated `kiam` before, because the architectural approach is attractive, but (at that time) there were a some significant down-sides. Have this issues been resolved?
1. The `kaim` master couldn't run on the same node as the `kaim` agents, because the agents blocked access to the AWS API. The suggestion is/was to run `kaim` server on the master nodes and run no agents there, but that isn't an option for managed control planes like EKS/GKE/AKE. And having a dedicate node-pool just for `kiam` seems like a large overhead.
2. The `kaim` architecture required a CA and x509 certificates between the server and agents, but had no way to self-issue or - most importantly - rotate them, creating a significant manual maintenance overhead. I suggested using `cert-manager` with a private CA to fix this, but I don't know if that or similar was ever implemented?
3. The required IAM roles and trust relationships were significantly more complex to configure and manage than `kube2iam`.

I've previously read the articles regards reported problems with `kube2iam` but - perhaps at our scale - we haven't seen any issues. And most common cited issues seem to have been patched, and the project continues to enjoys wide community support.

I definitely still think `kiam` is attractive, but the additional architectural complexity and management overhead have kept me away, since `kube2iam` works just great in our experience.

**Comment by mcfedr** [comment]
> `aws-alb-ingress-controller` would be so nice to have - `eksctl` provides very nice experience for creating the cluster, but once you want to make anything public with ingress then it's all manual

@artemyarulin I had a simpilar thought, and 30 mins free :) https://github.com/weaveworks/eksctl/pull/675

**Comment by artemyarulin** [comment]
@mcfedr That is awesome - thank you! 👍

**Comment by leakingtapan** [comment]
Those feature gates are beta as of 1.14. So I think it's fine to not do anything

**Comment by leakingtapan** [comment]
Speaking of EBS CSI driver, it is official supported by EKS since 1.14. Any plans for eksctl to support installation of the driver?

**Comment by whereisaaron** [comment]
@leakingtapan would be good to start testing, but it is hard for users to get excited until at least Volume Snapshots or Volume Resizing is supported. But that could a year away yet for EKS?
https://aws.amazon.com/blogs/opensource/eks-support-ebs-csi-driver/

**Comment by michaelbeaumont** [comment]
Closing this, please open any issues for specific issues you think might belong in `eksctl`.
