### ISSUE TITLE
[Bug] eksctl 0.98.0 throws error about Fargate in AWS China on delete

### ISSUE THREAD

**Issue by artem-nefedov** [weaveworks/eksctl#5319]
When running eksctl in AWS China partition (aws-cn), running `eksctl delete cluster` now throws an error and the process stops:

```
Error: failed to get Fargate profile(s) for cluster "my-cluster": operation error EKS: ListFargateProfiles, https response error StatusCode: 403, RequestID: 851072a6-f8a5-4c5b-aed5-a55c8777e97f, api error AccessDeniedException: Account <redacted> is not authorized to use this service
```

This is a regression in eksctl 0.98.0 (after migrating to SDK v2). Version 0.97.0 works fine.
Also, 0.98.0 doesn't have this problem on creation - only deletion is affected.

Note the following:
- Role has `eks:*` permissions for all resources
- [EKS Fargate is not supported in AWS China](https://docs.amazonaws.cn/en_us/aws/latest/userguide/eks.html)

In comparison, version 0.97.0 just prints an info message and proceeds with deletion:

```
[ℹ]  either account is not authorized to use Fargate or region cn-north-1 is not supported. Ignoring error
```

**Comment by cPu1** [comment]
> Looks like the version 0.99.0 has the same issue.

@maopei820219, this is not fixed yet. We'll try to get a fix out soon.

**Comment by maopei820219** [comment]
@cPu1 
Could this issue be fixed in the release 0.101.0-rc.0? I need an version include this fix and [#5248](https://github.com/weaveworks/eksctl/pull/5248).

**Comment by maopei820219** [comment]
@cPu1 
I will find some time tomorrow or this weekend to test it.

**Comment by maopei820219** [comment]
@cPu1 
I completed the testing. Your fix works as expected.
Here is what I did:
1. Create an EKS cluster in cn-north-1 region.
2. Use eksctl version 0.99.0 to run "eskctl delete cluster CLUSTER_NAME --region cn-north-1" command. It fails with the error:
> Error: failed to get Fargate profile(s) for cluster "CLUSTER_NAME": operation error EKS: ListFargateProfiles, https response error StatusCode: 403, RequestID: REQUEST_ID, api error AccessDeniedException: Account ACCOUNT_ID is not authorized to use this service
3. Checkout the code from the tag "v0.102.0-rc.0", build eksctl, run "eskctl delete cluster CLUSTER_NAME --region cn-north-1" command. The cluster is deleted successfully. (I don't use the Assets of Release 0.102.0, because it was not created when I run the testing.)
