### ISSUE TITLE
drain nodes on scale-down

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#586]
While working on #370, I realised that drain on scale-down will have to work differently from other operations. We will need to look into this, it might require an operator inside the cluster or maybe simply best left to auto-scaler to take care of - TBD.

**Comment by errordeveloper** [comment]
Having an long-running add-on for this may not be ideal. Alternatively we could use an equivalent of `autoscaling detach-instances --should-decrement-desired-capacity`, but that implies that CloudFormation will get out of date, but perhaps that can be dealt with separately and isn't a big deal.

**Comment by errordeveloper** [comment]
@mumoshu I believe cluster autoscaler performs drain on scale down, or do we need to use  something similar to [`kube-node-drainer-asg-status-updater`](https://github.com/kubernetes-incubator/kube-aws/blob/bdeadab166e728dbcc130ac3124affc66cc4d682/builtin/files/userdata/cloud-config-controller#L2333-L2543)

**Comment by whereisaaron** [comment]
Discussion and builds of automatic node draining for ASG in-scaling and Spot Fleet shutdowns, similar to `kube-aws` https://github.com/awslabs/amazon-eks-ami/issues/66

**Comment by toothbrush** [comment]
Hi there.  I'm currently being bitten by an issue that arises when nodes are removed from my node group.  It's because my apps don't come up healthy without working Istio (which we use, and whose myriad components are sometimes on the terminated node) and Istio takes rather long for all its bits to rediscover each other when gracelessly killed.  Instead, it'd be much better to drain then terminate nodes.

The linked issue, https://github.com/awslabs/amazon-eks-ami/issues/66, seems to be closed as `wontfix`, so i wonder if `eksctl` plans to introduce some magic to make this work out the box?  If it exists and i've missed it — my apologies! 🙌 

(of course it might be easier to ditch Istio, but for now i'd like to try and make it work, brittle as it is)

**Comment by toothbrush** [comment]
Incidentally, in a previous role at another company, we _did_ have a container running a service which would (i believe, if i remember correctly) simply poll a SNS queue for ASG termination events, then call `continue` on the ASG termination.  I forget the details, but it feels like it'd be a shame if i'd have to reïmplement something like that when using EKS.

**Comment by mumoshu** [comment]
@errordeveloper cluster-autoscaler does drain nodes and pods on scale down, but it happens only when an ASG being shrunk by CA. Is that what you target?

Once we add `eksctl update nodegroup` with a (optional?) support for doing rolling-update rather than blue-green deployment of the ASG, it is likely we need a "drain-on-termination" functionality. For that, something like `kube-node-drainer-asg-status-updater` would be useful.

**Comment by mumoshu** [comment]
I think we have several options from combinations of the messaging model(pull vs push) and where to run the controller(per-node agent in daemonset pod/systemd svc, a single leader-election-enabled critical pod in specific node/nodegroup/ns, lambda function, etc).

For pulling in lifecycle hook events, polling DescribeAutoScalingGroups or SQS queues (with the visibility timeout set to 0 if the controller is distributed across nodes) would work.

For push, we need SNS, CloudWatchEvents connected to a lambda function via some DNS name would be needed.

**Comment by richardcase** [comment]
@errordeveloper @mumoshu - could we not handle this using termination polices, instance protection. marking a node unschedulable and the Eviction API? One issue with this approach would be if eksctl terminated part way through the scale down operation.

**Comment by mumoshu** [comment]
> One issue with this approach would be if eksctl terminated part way through the scale down operation.

@richardcase Hey! I couldn't understand this part.

Are you talking about the case eksctl stopped in the middle of an update, especially while it is iterating each node/nodegroup by draining and then terminating?

**Comment by errordeveloper** [comment]
@richardcase I don't know much about termination policies.

Broadly speaking, if you use profiles, you can get cluster autoscaler, which is supposed to take care of draining, however `eksctl scale nodegroup` is not aware of cluster autoscaler.
