### ISSUE TITLE
review use of pagination in AWS API requests

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#590]
We should make use of pagination in all requests where we lookup multiple items, and SDK supports it.

For example, we currently use `ec2.DescribeNetworkInterfaces` here:
https://github.com/weaveworks/eksctl/blob/510fb269e62fbd68734df8ab655335ab014aa032/pkg/vpc/cleanup.go#L21-L36

This can easily return too many items, we should use `ec2.DescribeNetworkInterfacesPages` instead. I believe we need to update SDK for that, current version we use doesn't have it.

Also here we use `ec2.DescribeKeyPairs` in attempt of listing all key pairs, but there is no `ec2.DescribeKeyPairsPages`.

https://github.com/weaveworks/eksctl/blob/ee7e72febc80ff960e37648dd32c058f574567d1/pkg/eks/auth.go#L114-L131

**Comment by cPu1** [comment]
>Also here we use ec2.DescribeKeyPairs in attempt of listing all key pairs, but there is no ec2.DescribeKeyPairsPages.

We don't need to use pagination for `ec2.DescribeKeyPairs` since we're filtering out the result by the key pair name and expect the result to be exactly one value. This is also true for DescribeImages where the result is filtered by the AMI.
I think pagination isn't supported for `DescribeKeyPairs` since the maximum no. of key pairs one can have in EC2 is 5000, so maybe it'd return all of them in a single call.
