### ISSUE TITLE
[Bug] eksctl get fargateprofile doesn't get all fargate profiles

### ISSUE THREAD

**Issue by jetrohd** [weaveworks/eksctl#6239]
### What were you trying to accomplish?
eksctl get fargateprofile --cluster dcp-dev-be-eks -o yaml

### What happened?
I got some fargate profiles, but some are missing (fp-default, i.e.):

$ eksctl get fargateprofile --cluster dcp-dev-be-eks -o yaml | grep name:
- name: aftersales-email-notification-processor
- name: aftersales-finance-financialoverview-api
- name: aftersales-salesorders-api
- name: aftersales-salesorders-deliveries-eventprocessing
- name: aftersales-salesorders-openorder-api
- name: aftersales-salesorders-openorder-report
- name: aftersales-salesorders-orders-eventprocessing
- name: aftersales-salesorders-reference-data-eventprocessing
- name: aftersales-salesorders-shipments-eventprocessing
- name: aftersales-salesorders-track-and-trace-eventprocessing
- name: aftersales-salesorders-user-policies-eventprocessing
- name: channel-policies-api
- name: channel-stores-api
- name: channel-stores-eventprocessing
- name: customer-accounts-api
- name: customer-accounts-eventprocessing
- name: customer-policies-api
- name: customer-policies-eventprocessing
- name: customer-portfolio-calculator
- name: customer-portfolio-eventprocessing

### How to reproduce it?
When I launch the command the fp-default should be listed, but it's not (although I can see it created on the AWS console):
$ eksctl get fargateprofile --cluster dcp-dev-be-eks -o yaml | grep name:

If using a config file, include it here, removing any sensitive information!
-->

**Logs**

**Anything else we need to know?**
 no profiles, AWS variables and MFA

**Versions**

```
$ eksctl info
eksctl version: 0.128.0
kubectl version: v1.26.0
OS: windows
```

**Comment by AnuSharma51** [comment]
I have also faced the same issue.

Issue : I have 40 fargate profiles present in my EKS cluster. When I use command "eksctl get fargateprofile", it shows only the 20 fargate profiles alphabetically.

Expected behavior : It should show all 40 fargate profiles.

Actual behavior : It is only showing first 20 fargate profiles alphabetically.

I have checked with eksctl versions 0.125.0 and 0.128.0 and got the same result. Is this expected behavior? 

eksctl get fargateprofile --cluster fargate-cluster -o yaml --region eu-central-1 | grep name:
- name: appleprofile
- name: ballprofile
- name: catprofile
- name: dogprofile
- name: eggprofile
- name: fishprofile
- name: fp-default
- name: fp-dev
- name: fp-dev1
- name: fp-dev2
- name: fp-dev3
- name: fp-dev4
- name: fp-dev5
- name: fp-dev6
- name: fp-dev7
- name: fp-dev8
- name: gprofile
- name: hprofile
- name: iprofile
- name: jprofile

However, AWS console and aws cli is showing the expected result.

aws eks list-fargate-profiles --cluster-name fargate-cluster --region eu-central-1                       
{
    "fargateProfileNames": [
        "appleprofile",
        "ballprofile",
        "catprofile",
        "dogprofile",
        "eggprofile",
        "fishprofile",
        "fp-default",
        "fp-dev",
        "fp-dev1",
        "fp-dev2",
        "fp-dev3",
        "fp-dev4",
        "fp-dev5",
        "fp-dev6",
        "fp-dev7",
        "fp-dev8",
        "gprofile",
        "hprofile",
        "iprofile",
        "jprofile",
        "kprofile",
        "lprofile",
        "mprofile",
        "oprofile",
        "pprofile"
    ]
}
