### ISSUE TITLE
check if given instance type is available in the given region

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#636]
@martina-if mentioned this earlier, more info is needed. We could fix this by doing an API lookup, but I'm not 100% sure if there is an API for this.

**Comment by whereisaaron** [comment]
I ran into the problem in Sydney, where one AZ has no m5 instance types 😢 
Arguably my problem to check first, but a check/warning in `eksctl` would be welcome there is an easy/sane method to check via AWS API.

**Comment by errordeveloper** [comment]
Ah, didn't know it could be down to an AZ... We will need to figure if
there is an API, but also basic checks based on known instance type names
would be a good idea, as currently you can set instance type to anything
really and you will only get an error way too late. Also, we should
probably do a few things to help users who somehow got to the situation
where until nodegroup failed to create. I will open another issue for that.

**Comment by whereisaaron** [comment]
If you create a multi AZ nodegroup and one AZ can’t create the specified type, the nodegroup still successfully comes up. You just get an extra nodes in the capable AZ, and as ASG constantly cycles and raises errors trying and failing to replace instances with instances in the AZ that is not capable. The only symptoms are no nodes in one AZ, and constant ASG errors.

**Comment by errordeveloper** [comment]
@whereisaaron that's terrific. Where do you find those errors btw?

**Comment by whereisaaron** [comment]
You can see the errors under ASG -> Activity History in the console. It keeps say 'hey, let's balance this by launching m5 instances in AZ X, oh that didn't work'. Apparently the ASG controller is equally confusing by the Sydney situation. This is AZ '2b' in Sydney, which is notably the worst of the three, missing facilities, more failures. I think it was a co-lo rather than a dedicated build, to get two AZ in Sydney quickly to bootstrap the region.
