### ISSUE TITLE
OS volumes incorrectly configured for Windows managed nodegroups

### ISSUE THREAD

**Issue by rageanilkumar** [weaveworks/eksctl#6572]
Hi, 

We are facing volume issues while creating with eksctl yaml.

Issue : By default another volume is creating as OS DISK instead of taking from yaml file.

PFB yaml file which I am using for creating windows managed node group:

---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: nv-usdcpr-eks-01
  region: us-east-1
  tags:
    Project: USDC-prod
   
managedNodeGroups:
  - name: wsnode1
    amiFamily: WindowsServer2019FullContainer
    minSize: 1
    maxSize: 10
    desiredCapacity: 1
    volumeSize: 256
    volumeType: gp2
    volumeEncrypted: true
    volumekmsKeyID: 0aae7d13-2db9-4788-bab4-957ced22891f
    instanceType: r6a.2xlarge
    privateNetworking: true
    labels:
      sku: windows
    availabilityZones:
      - us-east-1a
      - us-east-1b
      - us-east-1c
    tags:
      Project: USDC-prod
   
Regards,
Rage Anilkumar

**Comment by TiberiuGC** [comment]
Hi @rageanilkumar , could you please share with me the volumes that you see in AWS Console and explain how do they differ from expectations? 🙏

**Comment by rageanilkumar** [comment]
Hi @TiberiuGC ,

PFB snapshot for your reference:

![image](https://user-images.githubusercontent.com/53990880/236457028-b2ee3336-832e-4e0e-ace7-5a4f44109ba1.png)

From console, Only one volume is creating.
Using eksctl yaml file, two volumes are creating. I.E one is default volume(50 GB) and second one is 256 GB (Mentioned volume size is 256 GB). 

Need to know why default volume is creating???

Could you please reproduce the same issue from end and let me know in case of any queries.

Regards,
Rage Anilkumar

**Comment by TiberiuGC** [comment]
Thanks a lot for coming back to me with this detailed view 🔥 .

I'm assuming from the console `/dev/sda1` is the only volume being created right?

I think the default volumes are always being created for all instance ami families, and what `eksctl` usually does is overwrite them with the values provided in the config file (i.e. size, type, kmsKeyID). However, for this particular case `eksctl` seems to think that the default volume should be called  `/dev/xvda` (the default for Linux images), so instead of overwriting the values for `/dev/sda1`, it incorrectly creates a second volume.

We will work on a fix to correctly setup default volume name for Windows images (i.e. `/dev/sda1`).

In the meantime I suspect you can workaround this bug by specifying - `volumeName: /dev/sda1` in the config file.
