### ISSUE TITLE
Use tigher IAM role permissions

### ISSUE THREAD

**Issue by trondhindenes** [weaveworks/eksctl#661]
**What happened?**
When creating a nodegroup, I noticed that the IAM role attached is very wide:
```

            "Action": [
                "autoscaling:DescribeAutoScalingGroups",
                "autoscaling:DescribeAutoScalingInstances",
                "autoscaling:DescribeLaunchConfigurations",
                "autoscaling:DescribeTags",
                "autoscaling:SetDesiredCapacity",
                "autoscaling:TerminateInstanceInAutoScalingGroup"
            ],
            "Resource": "*",
            "Effect": "Allow"
        }
    ]
```
**What you expected to happen?**
Since we know the name of the autoscaling group, the `SetDesiredCapacity` and `TerminateInstanceInAutoScalingGroup` actions should be moved to a separate permissions block, scoped to the current ASG for the nodegroup.

**Comment by whereisaaron** [comment]
Hi @trondhindenes the permission are correct as is. These permissions the [required permissions](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md#scaling-a-node-group-to-0) to enable the `cluster-autoscaler` with `--node-group-auto-discovery` and scaling node groups to 0.

> Since we know the name of the autoscaling group, the SetDesiredCapacity and TerminateInstanceInAutoScalingGroup actions should be moved to a separate permissions block, scoped to the current ASG for the nodegroup.

What? Why? This would break the `cluster-autoscaler` as it would be unable to scale an ASG not where it, itself, is running.

Please read the `cluster-autoscaler` documentation before commenting.
https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md

These permissions were only added to you cluster because you specifically requested they be added with the `--asg-access` option. Just remove that option and they won't be added.

If you want to reduce the scope of these permissions and use the auto-scaler. Don't add them to the worker role at all, instead assign them to a separate role. Install [`kube2iam`](https://blog.csanchez.org/2018/11/14/installing-kube2iam-in-aws-kubernetes-eks-cluster/) or [`kaim`](https://github.com/uswitch/kiam) on your cluster, and then map that role directly to the `cluster-autoscaler` Pod.

**Comment by errordeveloper** [comment]
Another option to consider is a custom policy instead of canned policies.

You can specify it like this:
```
nodeGroups:
  - name: ng-1
    instanceType: m5.large
    minSize: 5
    maxSize: 10
    iam:
      instanceRoleARN: "arn:aws:iam::123:role/Custom_EKS_ASG_Policy"
```

**Comment by errordeveloper** [comment]
@trondhindenes please let us know if it's okay to close the issue!

**Comment by trondhindenes** [comment]
@errordeveloper yeah. Noticing that the cluster-autoscaler itself documents the permissions set which eksctl configures, so it's an upstream issue more than an eksctl issue I guess. Okay to close.

**Comment by errordeveloper** [comment]
Thanks for let us know!
