### ISSUE TITLE
1.11 -> 1.12 upgrade docs

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#684]
We haven't updated the readme after #680 landed, we should do it soon. The main part is addition of `update-coredns` command, but it's worse documenting that one has to upgrade one version at a time.

**Comment by errordeveloper** [comment]
@christopherhein would you like to do this?

**Comment by errordeveloper** [comment]
@christopherhein I've pushed  887f097 assuming you have nothing to add, but please config.

**Comment by whereisaaron** [comment]
It would be nice to document if `eksctl` 0.1.27 uses the [CloudFormation support for upgrading the cluster](https://github.com/aws/containers-roadmap/issues/115#issuecomment-477843308)? Or does it bypass the CF stack and user the EKS API? I was holding off upgrading because I didn't want the control plane CF stack to drift and not be usable.

**Comment by errordeveloper** [comment]
It currently uses the EKS API directly, we have
https://github.com/weaveworks/eksctl/issues/683 track that.
