### ISSUE TITLE
ENI tagging

### ISSUE THREAD

**Issue by cdenneen** [weaveworks/eksctl#751]
Notice no tagging on any of these ENI's created.
Description for Worker Nodes isn't consistent.
Also not sure why one of the 2 nodes has 2 ENIs and the other has 1.

<img width="1204" alt="Screen Shot 2019-04-24 at 12 06 32 PM" src="https://user-images.githubusercontent.com/720097/56675446-11b36400-668a-11e9-95e9-b4f0524be577.png">

**Comment by errordeveloper** [comment]
Thanks for reporting this @cdenneen! Unfortunately, this is outside of our control. These ENIs are managed by [the network driver](https://github.com/aws/amazon-vpc-cni-k8s). I believe that some ENIs also get created by EKS itself, but I'm not fully familiar with those, it's really an implementation detail to me and I would guess that in the future that area may evolve.
The first two ENIs appear like primary ENIs of the nodes that are not used by the network drive, that's why they only have primary IPs and and different description format. The driver uses non-primary ENIs, it creates those and allocates IPs as needed for scheduling pods, but doesn't automatically garbage collect when pods go away.

**Comment by errordeveloper** [comment]
@christopherhein @tiffanyfay do you think we should open an issue elsewhere? Any other thoughts on this?

**Comment by whereisaaron** [comment]
Despite tags for EIP being added to AWS API back in 2017, AWS CloudFormation is yet to support them 😭

**Comment by whereisaaron** [comment]
We can track our wait for CF EIP support here:
https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/84

**Comment by josegonzalez** [comment]
Seems this was added in November to CF :)
