### ISSUE TITLE
Helm init fails with User "system:anonymous" cannot create resource "deployments" in API group "extensions" in the namespace "kube-system"

### ISSUE THREAD

**Issue by pcm32** [weaveworks/eksctl#757]
**What help do you need?**

Helm init on eksctl provisioned cluster:

```
helm init --upgrade --service-account=tiller --wait
```

fails with:

```
$HELM_HOME has been configured at /Users/pmoreno/.helm.
Error: error installing: deployments.extensions is forbidden: User "system:anonymous" cannot create resource "deployments" in API group "extensions" in the namespace "kube-system"
```

This is after following different approaches to try to set up a service account and clusterrolebinding, such as:

```
$ kubectl -n kube-system create sa tiller
serviceaccount/tiller created
$ kubectl create clusterrolebinding tiller-cluster-rule \
>     --clusterrole=cluster-admin \
>     --serviceaccount=kube-system:tiller 
```

I'm aware that you have an option to add helm on `eksctl create cluster`, but I should be able to run helm against an already create cluster as well, right? I see that there are plans to add the helm addon to a running cluster, but couldn't find the way to do it? Or am I doing something wrong?

Thanks!

**Comment by errordeveloper** [comment]
Actually helm add-on is only a roadmap item, we don't have it yet.

The error message you are getting refers to `system:anonymous`, which means you are not authenticated properly.

This typically happens when you have an old Kubernetes client that doesn't know about EKS authenticator plugin. So you appear to have a recent version of `kubectl` that works just fine, but `helm` needs to be upgraded also.

**Comment by errordeveloper** [comment]
@pcm32 did you manage to solve this?

**Comment by pcm32** [comment]
Yes, thanks, newer versions of kubectl and helm worked like a charm as suggested! Sorry for not coming back promptly.
