### ISSUE TITLE
Dynamically lookup DeviceName for AMIs

### ISSUE THREAD

**Issue by adamjohnson01** [weaveworks/eksctl#774]
**Why do you want this feature?**
We are using a custom ami which uses /dev/sda1 for the root device, currently there is no way for us extend the root volume of the ami as the launch configuration will add another disk using /dev/xvda 

**What feature/behavior/change do you want?**
We would like the ability to override the DeviceName value using a value in the config file

**Comment by errordeveloper** [comment]
Would you mind sharing more info about the kind AMI that depends on this? Is it an in-house thing for you, or one from the marketplace or elsewhere?

**Comment by adamjohnson01** [comment]
No problem, the official Redhat and Centos AMIs use /dev/sda1 for the root device. We build our images on top of those.

**Comment by errordeveloper** [comment]
That sounds relatively mainstream to me, perhaps we can add image families
for those and set device name based on the family, wdyt?

**Comment by adamjohnson01** [comment]
Just to clarify, when I say official Redhat/Centos I am referring to the base images, there are no eks images available, we build and maintain our own private eks images.

I think rather than hard coding values it may be a better idea to a populate the value dynamically, the information can be retrieved by describing the ami that is going to be used, this would make it a lot more flexible and remove the need to override anything.

**Comment by errordeveloper** [comment]
That is a very good point indeed. Let's focus on retrieving it, rather then
hardcoding.
We may still want to add more parameters later, but I think the issue at
hand is that there is a hardcoded value now that needs to be dynamically
resolved based on AMI used.

Beside that, I think we should open another issue to discuss RH image
family, even if there is no public AMI, I think we should discuss whether a
family should be defined instead of falling back on built-in AL2 family
definition.

**Comment by adamjohnson01** [comment]
Cool, I will close my other pull request and work on getting the value dynamically. 

I think that having a RH family makes sense, happy to discuss it in another issue.
