### ISSUE TITLE
Update KubeConfig Generation to use aws cli get-token

### ISSUE THREAD

**Issue by christopherhein** [weaveworks/eksctl#788]
**Why do you want this feature?**
This will remove some dependencies for you to install when using `eks` and `eksctl`.

**What feature/behavior/change do you want?**
Change the Kubeconfig generation to use the `get-token` command once it's merged and released - https://github.com/aws/aws-cli/pull/4141

**Comment by errordeveloper** [comment]
Are you suggesting one would be able to use AWS CLI instead of authenticator?

**Comment by christopherhein** [comment]
Yeah, if you download the latest `awscli` you can now use that to run `aws eks get-token` instead of the authenticator. Reducing dependencies needed to get up and running eks

**Comment by errordeveloper** [comment]
Hm, ok. We don't depend on authenticator for things that eksctl does, we
only recommend user to install authenticator, so that they can use it with
kubectl.

Which one should a user install if they haven't got either and don't care
about details? Seems like Python could be a problem, which potentially
easier to install via package manager, while authenticator has to be
installed with curl or something like that, so I am honestly not sure which
one is best to recommend. Seems like too much cognitive overhead.

**Comment by christopherhein** [comment]
The difference here is if they use any other AWS API they will typically have the AWS CLI installed which is what I mean by reducing the dependencies. We updated the `aws eks update-kubeconfig` to use the exec credential command using the aws cli so this would be a relatively simple change with some docs updates.

**Comment by errordeveloper** [comment]
Understood, as I said, sounds plausible to try detecting when the right version of AWS CLI is installed and setting that in generated kubeconfig.
