### ISSUE TITLE
eksctl delete cluster not works 

### ISSUE THREAD

**Issue by mmaryo** [weaveworks/eksctl#790]
Hello 

I just create a cluster 

    eksctl create cluster  --name mario-cluster ....

Then I try to remove it 

```
~ eksctl delete cluster mario-cluster                           
[ℹ]  using region us-east-1
[ℹ]  deleting EKS cluster "mario-cluster"
[✖]  no eksctl-managed CloudFormation stacks found for "mario-cluster"
```

I look into CloudFormation, I see "eksctl-mario-cluster-cluster", so I try 

```
~ eksctl delete cluster eksctl-mario-cluster-cluster   
[ℹ]  using region us-east-1
[ℹ]  deleting EKS cluster "eksctl-mario-cluster-cluster"
[✖]  no eksctl-managed CloudFormation stacks found for "eksctl-mario-cluster-cluster"
```

Is it a bug ?

**Comment by martina-if** [comment]
Hi @mmaryo, which region did you use when you created the cluster? What happens if you run `eksctl get clusters`? 

Feel free to reach us on [slack](https://weave-community.slack.com/messages/eksctl) :)

**Comment by mmaryo** [comment]
➜  ~ eksctl get clusters            
NAME	REGION
dev	us-east-1
prod	us-east-1

And I create cluster in ap-south-1

**Comment by whereisaaron** [comment]
Hi. If you are not using you default region, then you need to specify, for both `get` and `delete.
```
eksctl get cluster [--name=<name>] [--region=<region>]
```

**Comment by mmaryo** [comment]
thanks it works

    ➜  ~ eksctl delete cluster --name=mario-test-2 --region=ap-south-1
    [ℹ]  using region ap-south-1
    [ℹ]  deleting EKS cluster "mario-test-2"
    [✔]  kubeconfig has been updated
    [ℹ]  2 sequential tasks: { delete nodegroup "ng-d6dd6593", delete cluster control plane "mario-test-2" 
    [async] }
    [ℹ]  will delete stack "eksctl-mario-test-2-nodegroup-ng-d6dd6593"
    [ℹ]  waiting for stack "eksctl-mario-test-2-nodegroup-ng-d6dd6593" to get deleted
    [ℹ]  will delete stack "eksctl-mario-test-2-cluster"
    [✔]  all cluster resources were deleted


However deletion of CloudFormation failed as you can see on picture 

![Screenshot 2019-05-13 13:56:00](https://user-images.githubusercontent.com/1669985/57619769-12ebf880-7587-11e9-9208-fe1c675655d2.png)

**Comment by whereisaaron** [comment]
Probably some dependent resource has been created that blocks the stack delete, you’d have to check CloudFormation events to see what.

**Comment by Daddy-Badger** [comment]
I have similar issue on the delete stack.  Have found that the cloudformation tear down always fails on gateway / vpc subnet deletion due to a dependancy.  This is due to the loadbalancer not being deleted.  If you manually delete the ELB then the CF script picks up again and deletes the VPC, ENI, Subnets and SGs.

Using [ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.1.33"}

<img width="849" alt="Screenshot 2019-06-05 at 23 37 55" src="https://user-images.githubusercontent.com/13080291/58995241-42d79600-87eb-11e9-94e8-551014c84272.png">
<img width="855" alt="Screenshot 2019-06-05 at 23 40 32" src="https://user-images.githubusercontent.com/13080291/58995252-5682fc80-87eb-11e9-8ca4-6a5737dc1848.png">

**Comment by martina-if** [comment]
I am closing this since it's from a very old version of eksctl. @Daddy-Badger @mmaryo if you are still having issues the workaround is to delete the AWS resources in the right order taking into account the dependencies between them (first the gateway, then the VPC and then the cluster stack). Feel free to reopen it if you still see this issue with eksctl 0.12.0+.

**Comment by ClashLuke** [comment]
Loadbalancer issue is resolved in the new version of eksctl. Unforunately, a mounted EFS volume blocks the removal as well. As this has nothing to do with eksctl, but instead is an issue with cloudformation's removal policy, I do not believe that reopening this issue is appropiate.\
