### ISSUE TITLE
Bash completion doesn't work in bash 3

### ISSUE THREAD

**Issue by boillodmanuel** [weaveworks/eksctl#803]
**What happened?**
Sourcing from process substitution in bash 3 doesn't work, so `. <(eksctl completion bash)` does not work

**Anything else we need to know?**
The working command is `source /dev/stdin <<<"$(eksctl completion bash)"`

**Versions**
Please paste in the output of these commands:
```
$ eksctl version
[ℹ]  version.Info{BuiltAt:"", GitCommit:"", GitTag:"0.1.32"}
```

**Comment by martina-if** [comment]
Hi @boillodmanuel , thank you for the report. 

Out of curiosity, which distro are you using? I am curious because I think bash 4.0 was released in like 2009.

**Comment by whereisaaron** [comment]
Heh, I’m guessing a Mac @martina-if, they are stuck in a time loop on bash 3.2. 2007 was the last time [Macs were important to Apple revenue](https://www.statista.com/statistics/263401/global-apple-iphone-sales-since-3rd-quarter-2007/) and also the last time they updated bash.

@boillodmanuel there are workarounds to upgrade `bash`:
https://itnext.io/upgrading-bash-on-macos-7138bd1066ba

**Comment by boillodmanuel** [comment]
Exactly, on mac!

@whereisaaron thanks for the link ;)

**Comment by martina-if** [comment]
Wow, I didn't know this. Thanks Aaron for the links!
