### ISSUE TITLE
Add reference document mapping config YAML attributes to equivalent CLI options

### ISSUE THREAD

**Issue by sbernheim** [weaveworks/eksctl#921]
Add a reference page in `eksctl` documentation that maps command-line params to their equivalent attributes in YAML configs.

For example: `autoScaler: true` in the iam.withAddonPolicies (as in here https://github.com/weaveworks/eksctl/blob/documentation/site/content/usage/09-iam-policies.md) maps to the equivalent CLI option `create cluster ---asg-access`.

**Comment by errordeveloper** [comment]
We also have #633, which was meant to be a way of automating this, which should be relatively easy to implement - wdyt?

**Comment by kalbir** [comment]
I think we need to get some docs out into the world sooner rather than later. So we'll prioritise getting the documentation written. 

It may be that the approach described in #633 is the best way to do it (and that approach would be good in the long run for keeping them up to date). But we can leave that up to whoever takes up this issue.

**Comment by gemagomez** [comment]
Let's discuss on the approach before starting implementation. Whoever picks this item should be starting that discussion before implementing.

**Comment by marccarre** [comment]
> a way of automating this

+1. Documentation tends to quickly "_rot_" otherwise. I understand we want to have something written quickly, and that's fine proceeding manually for _now_. However medium/longer term, a way to keep such documentation close to the code and to be able to re-generate the documentation would make things a lot easier to maintain, especially as new commands, flags, etc. are added, and `ClusterConfig` evolves.

**Comment by kalbir** [comment]
Yes. Initially we didn’t prioritise this as we thought that we could get a quick fix with a manual update. But I think we now need to put it into play in an upcoming release.
