### ISSUE TITLE
read clusterName from kubeconfig

### ISSUE THREAD

**Issue by sdarwin** [weaveworks/eksctl#950]
**What feature/behavior/change do you want?**
Correct me if this is wrong, but when issuing a command like "eksctl create nodegroup --cluster=clusterName", the clusterName is required?

It would be convenient to follow what kops does. The message would be "Using cluster from kubectl context". You don't have to specify clusterName if there is a default context set in ~/.kube/config

**Why do you want this feature?**

Many eksctl commands require "--cluster=<clusterName>", however it's usually the same value again and again (which is the cluster you are working with at the moment).   There's the potential to make this more concise and usable.

**Comment by martina-if** [comment]
Hi @sdarwin, thank you for the feature request. This is a good idea. We will discuss it in the team.

**Comment by whereisaaron** [comment]
I see the appeal of skipping the repeated option, and for coupling `eksctl` and `kubectl` but I worry about assuming the current `kubectl` cluster is the one the user wants to `eksctl update` or gulp, `ekstl delete`.

Another option - instead or as well as. Since `eksctl` is designed to be primarily based around the config file. If the config file includes the cluster name, than specifying the config file for commands should be enough.

If we further introduce an environment variable `EKSCTL_CONFIG` than can be pointed at the config file for a cluster of our choice, then we can avoid have to repeatedly specific both the `--cluster`/`--name` options (why two option names for the same thing 😕) as @sdarwin would like, *and* we can avoid the `--config-file` option as well, for commands that need that.

**Comment by sdarwin** [comment]
Hi @whereisaaron ,

> "or gulp, ekstl delete."  

Good point. 

That should be an exceptional case, and  require the --name parameter.  Again, notice how kops handles it:

```
# kops delete cluster

--name is required (for safety)
```

>  specifying the config file, or EKSCTL_CONFIG 

Just a first impression, but that seems like it's adding an unnecessary layer of complexity.   The kubeconfig file is already pointing to the cluster that the user is interacting with.  It seems like a logical choice to use the info.  There's a quote, "Everything should be made as simple as possible... "
